### ISSUE TITLE
Consider using center of triangle bounds rather than centroid

### ISSUE THREAD

**Issue by mqp** [gkjohnson/three-mesh-bvh#105]
Right now, we use triangle centroids for several purposes in BVH construction:

- For determining the average of a triangle set on an axis when using the AVERAGE strategy.
- For determining the SAH planes for triangles on an axis when using the SAH strategy.
- For partitioning triangles after deciding on a split.

I suggest that it might be better to use the center of the bounds of the triangle (i.e. `(min + max) / 2`). Reasons:

- Construction should be more efficient. We won't have to allocate and compute a separate `centroids` array at all; we can store the triangle bounds as the center plus an offset, instead of a min and a max. That means we will have better data locality during construction and partitioning will be cheaper, because it won't have to swap centroids.
- The CENTER strategy will do a better job. Right now, the CENTER strategy first finds the split axis based on the bounds of the node. Then, it takes the center of those bounds to be the split position. But then, it partitions based on the centroids. This introduces a real risk that it could put all or most of the triangles on the same side, if the triangles are lengthy on the split axis relative to their distance apart. If it also partitioned based on the center of the bounds, the only case in which all of the triangles will go to the same side is if there's one triangle which spans the whole bounds of the node, and whose center is equal to the center of the node, and then many more triangles on one side of it. (Well, technically there might also be floating-point error cases.)
- It doesn't seem like it should make much difference to the AVERAGE or SAH strategies.

**Comment by mqp** [comment]
Here's a Hubs scene GLB containing a car model where using the center-of-bounds rather than the centroid greatly reduces the number of "bad splits" where all the triangles go on one side:

https://uploads-dev.reticulum.io/files/7d922ddb-6092-4524-84ed-411845d4a19e.glb

**Comment by gkjohnson** [comment]
This sounds like a good change to me! I don't recall a particular reason why the average of the vertices is being used to calculate the center. And in the case of long skinny triangles this should yield a better center value instead of weighting it towards the edge with two close verts.

The only thing I can think of is that this could result in a "center" point that lies outside of the triangle but I'm not immediately seeing how that would be a problem.

**Comment by mqp** [comment]
I just picked the centroid back then because it was easy to compute and seemed like a natural center-of-the-triangle to use. I don't know any correctness-related reason to prefer it. It seems to me like we could pick literally any point which is a function of the triangle and the raycasting would still be correct, so it's just a matter of convenience.
