### ISSUE TITLE
Missing Intersection due to floating point precision

### ISSUE THREAD

**Issue by obsius** [gkjohnson/three-mesh-bvh#112]
I've got an edge case where I have a single point that fails to raycast depending on what mode I use.  Using CENTER it returns a point, but using AVERAGE it returns nothing, even though the ray intersects the surface.  I was using a version of this library that I modified a few months ago (I had temporarily applied an overflow fix), but just recently deleted that and went back to sourcing from NPM, which bumped me up to the latest version.  If I use that older version it doesn't have this issue.  I don't know the internals that well, but I'm guessing maybe the point is outside of any indexes and falls through cracks so to speak.

I'll dump the triangulation data if I can figure out how to.

**Comment by gkjohnson** [comment]
Yeah it would be great to have some test data. Does it not work at all with `AVERAGE` with any mesh?

`CENTER` is the most well tested split strategy at the moment and unfortunately we don't have tests for the other couple split types so my best suggestion for a workaround until this is fixed is to use the default `CENTER` type of split. Is there a reason you're using AVERAGE? If that's a preferred split method for some reason it might be worth putting time into polishing up that code path and adding some tests.

**Comment by obsius** [comment]
[points.txt](https://drive.google.com/file/d/1UmYyqo202qDpeWRuazU4zkNrCrs0axpG/view?usp=sharing)

```js
points.txt: JSON stringified version of a Float32Array
Raycast X Y: 101086.2438562272 99421.40510391879


points; // points.txt as Float32Array
x; // x
y; // y

let geometry = new THREE.BufferGeometry();

geometry.addAttribute('position', new THREE.BufferAttribute(points, 3));
geometry.computeVertexNormals();
geometry.boundsTree = new BVH(geometry, {
	strategy: AVERAGE,
	maxDepth: 64,
	maxLeafTris: 16
});

let mesh = new THREE.Mesh(geometry);

let raycaster = new THREE.Raycaster();
raycaster.firstHitOnly = true;


raycaster.set(new THREE.Vector3(x, y, -1000), new THREE.Vector3(0, 0, 1));
raycaster.intersectObject(mesh);
```

**Comment by obsius** [comment]
Average is about 5x faster with these parameters, but maybe with different ones center would be quicker.  Not all of the rays are vertical like in this example, but the error condition happens with this ray.

**Comment by obsius** [comment]
And average is working almost all the time, in this case I did 16k raycasts, and only this 1 failed.  I have never seen this error with a different mesh.

**Comment by gkjohnson** [comment]
Interesting intuitively it seems like AVERAGE should be slower. I added a benchmark and it looks like AVERAGE is occasionally marginally faster or at least even with CENTER:

```
Compute BVH (CENTER)     : 207.6 ms
Compute BVH (AVERAGE)    : 200 ms
Compute BVH (SAH)        : 6154 ms
```

I'll add test cases for the SAH and AVERAGE split strategies and a specific use case for the data you've provided (if it's okay to host it in the repo) as a first step.

**Comment by gkjohnson** [comment]
Also if you're interested in poking around at all tree gets built in the [_buildTree](https://github.com/gkjohnson/three-mesh-bvh/blob/master/src/MeshBVH.js#L102) function and the AVERAGE split is calculated in the [getOptimalSplit](https://github.com/gkjohnson/three-mesh-bvh/blob/master/src/BVHConstructionContext.js#L217) function.

> If I use that older version it doesn't have this issue.

Do you recall which version of the library you were using?

**Comment by gkjohnson** [comment]
@obsius I've added some tests that show the AVERAGE split failure in #113 -- do you recall which version of the library you were using when this worked so there's a hint of somewhere to start looking?

Thanks!

**Comment by obsius** [comment]
Sorry for the delay, I've been on vacation.  I believe the version was 0.1.0.  Just to clarify about the performance, I didn't benchmark the compute time but rather the time to do lots of raycasts.  I'm not sure about the parameters I'm using, maybe if I tweaked those I'd see a reversal in performance.

**Comment by gkjohnson** [comment]
Of course no rush! Thanks for the information. I'll add benchmark for raycasts of the different split methods, as well -- I actually would expect that part to be faster. I'll take a look at what changed from 0.1.0.

Out of curiosity what kind of performance are you seeing for a raycast against your model and how many casts are you doing per frame?

**Comment by mqp** [comment]
FWIW, I definitely like the AVERAGE split method as a compromise that is much faster than building an SAH tree but has a much better worst-case tree that results when you build it with geometries that have "long" triangles.

**Comment by gkjohnson** [comment]
I haven't forgotten about this! A quick update:

I ran the new tests from #113 against the previous versions and it looks like it breaks between `0.1.2` and `0.1.3`. Specifically the tests pass before #106 is merged (f496a17cdf99b831efc911990932f8093600214a) and fails after (579116d2ab243ee003828e82b722725359e0294d).

@mqp I'll keep digging when I have a moment but I don't know if you have any thoughts. It's unclear whether or not that broke AVERAGE split or if it's broken in other ways and that change happened to cause this particular case to fail.

**Comment by gkjohnson** [comment]
New update:

The geometry you provided is pretty far off center (with a bounding box min and max of around `100928, 99222, 3541` and `101194, 99508, 3644`) so I tried centering the geometry and offsetting the ray by the same amount. That seems to "fix" the problem and the previously failing tests pass.

You can see and verify the centering changes to the geometry in the test in PR #119. The returned intersection contains the same face and vertex indices before and after the change, as well (looking at the value from the three.js implementation). I'm thinking it must be a floating point precision issue?

It looks like the values in the [getAverage](https://github.com/gkjohnson/three-mesh-bvh/blob/master/src/BVHConstructionContext.js#L74-L87) function would get pretty large in a case like this I wonder if something's being lost there.

**Comment by obsius** [comment]
Thanks for this, much appreciated.  That would make sense, I observed odd behavior when rendering a grid and had to do a similar thing.  I had a BufferGeometry which was equal sized cubes aligned to a grid, and I was seeing adjacent blocks look different sizes.  It came down to a floating point issue that I think is a result of shaders only supporting single precision floats.  When I pre processed all the data to a common center, I got visually uniform sizes.  I'm actually using this library both on data that I visualize, and data that is never visualized where I don't bother centering it.  Seeing that it uses a Float32Array under the hood I think you're right about a precision issue.  I have no issues centering this too, I don't think it'll affect creation or raycast performance by much.

**Comment by gkjohnson** [comment]
Glad to hear it. It's not the most satisfying answer but at least it can be worked around. I'll leave this open in case there are any ideas on how to address this in the BVH implementation and note this as a limitation in the documentation, for now.

**Comment by gkjohnson** [comment]
@obsius do you mind if I keep the geometry data you provided in the repo for the sake of testing this later on? It's added in #113 but I haven't merged it, yet.

**Comment by obsius** [comment]
Sure, that's fine.  Thanks for the help.

**Comment by gkjohnson** [comment]
I'm gonna close this because ultimately I don't thin there's a lot we can do about what seems to be floating point precision issues here. If you have any other suggestions let me know and we can reopen this!
