### ISSUE TITLE
Wrong nearest intersection with firstHitOnly=true 

### ISSUE THREAD

**Issue by Filyus** [gkjohnson/three-mesh-bvh#140]
Sometimes with firstHitOnly=true this library returns the wrong nearest intersection. With firstHitOnly=false there is no such problem, but I don't need all the intersections. Perhaps this was done for speed, but is there a compromise?
The SAH strategy is used.

**Comment by gkjohnson** [comment]
Hey @Filyus! Thanks for the report. Can you put together a simple example to demonstrate the problem?

**Comment by gkjohnson** [comment]
@Filyus I wanted to check in again about a repro case. Unfortunately I can't address the issue if I can reproduce it myself and the problem isn't present in the tests and demo scene.

**Comment by gkjohnson** [comment]
Closing because I don't have enough data to reproduce the problem with. Feel free to open another issue with more information.
