### ISSUE TITLE
Using bvh.shapecast() with moving Meshes

### ISSUE THREAD

**Issue by vatro** [gkjohnson/three-mesh-bvh#154]
Hi Garrett! :)

I have a **question** concerning using **bvh.shapecast** in your [collectTriangles example](https://gkjohnson.github.io/three-mesh-bvh/example/bundle/collectTriangles.html).
I needed it to work with **moving Meshes**, so I had to change [this part](https://github.com/gkjohnson/three-mesh-bvh/blob/d72aff6b09780b5f5c1d22bffda20e9a194df6be/example/collectTriangles.js#L195-L206) to this:

```javascript
...

bvh.shapecast(
    targetMesh,
    box => sphere.intersectsBox( box.applyMatrix4(targetMesh.matrixWorld)),
    ( tri, a, b, c ) => {
        tri.a.applyMatrix4(targetMesh.matrixWorld)
        tri.b.applyMatrix4(targetMesh.matrixWorld)
        tri.c.applyMatrix4(targetMesh.matrixWorld)

        if ( sphereIntersectTriangle( sphere, tri ) ) {
              indices.push( a, b, c );
         }
         
          return false
     }
...
```

It works, but I'd like to make sure that it's really the correct / only way to achieve this.
Thanks in advance for a short feedback! 👍

☝️ _I got a bit confused by this, because the Mesh in your [raycast demo](https://gkjohnson.github.io/three-mesh-bvh/example/bundle/raycast.html) is rotating and can also be moved while being correctly raycasted without the need to apply any extra transforms. I assumed bvh.shapecast() would also work with rotating / moving objects "out of the box"._

**Comment by gkjohnson** [comment]
Hey!

That's definitely a valid way to do it but of course you incur the overhead of applying the matrix transform to each vertex and bounding box. Another more performant option is to transform whatever shape you're intersecting with into the local frame of the mesh so only a single matrix multiplication has to happen. This is effectively what three.js does before performing raycasting by transforming your ray from world space to the local space of each mesh before checking triangle intersections. I haven't tested it but here's how I believe the code should look to do that with shapecast:

```js
const inverseMatrix = new THREE.Matrix4();
inverseMatrix.getInverse( targetMesh.matrixWorld );

const sphere = new THREE.Sphere( brushMesh.position, params.size );
sphere.applyMatrix4( inverseMatrix );

const indices = [];
targetMesh.geometry.bvh.shapecast(
	targetMesh,
	box => sphere.intersectsBox( box ),
	( tri, a, b, c ) => {

		if ( sphereIntersectTriangle( sphere, tri ) ) {

			indices.push( a, b, c );

		}

		return false;

	}
);
```

One thing to note in both approaches is that in three.js applying matrix transforms to bounding boxes and spheres will not preserve non uniform scaling embedded in the transformation so you'll probably get unexpected results if the mesh being cast against has a non uniform scale and rotation applied to it. It's possible to make that work but it likely means making your own intermediate box and sphere classes that respect skew transformations. Your approach may actually be more resilient to these issues those because I believe applying the matrix to the bounding box will give a conservative AABB result that encompasses the newly rotated bounds -- you'll wind up comparing against more triangles but the results should be correct if I'm thinking about it right. That's a trade to make, though.

Let me know if that clears things up! And thanks for bringing this up! It's a bit of an oversight in the example code, I think. If you have the interest and the time I'd definitely take a PR that clarifies the use in that example!

**Comment by vatro** [comment]
Cool, thank you for the valuable insights!  😎

> That's definitely a valid way to do it but of course you incur the overhead of applying the matrix transform to each vertex and bounding box

Yes, that's what I was thinking too, I'll measure the exact performance impact -> transformed (translated / rotated) vs. non-transformed Mesh.

> I haven't tested it but here's how I believe the code should look to do that with shapecast

It's **working**! 👍 ... though I had to position the `sphere` to `res[ 0 ].point` and **not** to `brushMesh.position`, otherwise the `brushMesh`s position is off 🤔, don't yet understand why 🤔 (?)

AND it seems to even work with **non-uniform scaling + rotation**! 👀

```javascript
function render() {

...

// Collect Triangles Example : Rotating / Moving  Mesh - 2nd Approach

		targetMesh.rotation.x -= 0.004
		targetMesh.rotation.y -= 0.004
		targetMesh.position.x = Math.sin(performance.now()*0.005)*0.2
		const tScaleX = 1 + Math.sin(performance.now()*0.005)*0.2
		const tScaleY = 1 + Math.cos(performance.now()*0.005)*0.2
		const tScaleZ = 1 + Math.sin(performance.now()*0.005)*0.3
		targetMesh.scale.set(tScaleX, tScaleY, tScaleZ)

		const res = raycaster.intersectObject( targetMesh, true );
		if ( res.length ) {

			brushMesh.position.copy( res[ 0 ].point );
			controls.enabled = false;
			brushMesh.visible = true;

			const inverseMatrix = new THREE.Matrix4();
			inverseMatrix.getInverse( targetMesh.matrixWorld );	

			const sphere = new THREE.Sphere( res[ 0 ].point, params.size );
			sphere.applyMatrix4( inverseMatrix );

			const indices = [];
			bvh.shapecast(
				targetMesh,
				box => sphere.intersectsBox( box ),
				( tri, a, b, c ) => {

				if ( sphereIntersectTriangle( sphere, tri ) ) {

					indices.push( a, b, c );

				}

				return false;

				}
			);

...
}
```
![three-mesh-bvh-collecttris-moving](https://user-images.githubusercontent.com/3778969/97973564-91b1a280-1dc6-11eb-95d7-06f04537020e.gif)




> If you have the interest and the time I'd definitely take a PR that clarifies the use in that example!

Sure, I'll be glad to! 🙂

**Comment by gkjohnson** [comment]
Nice!

> It's working! 👍 ... though I had to position the sphere to res[ 0 ].point and not to brushMesh.position, otherwise the brushMesh's position is off 🤔, don't yet understand why 🤔 (?)

Looks like Sphere [retains the reference to the vector you pass into it](https://github.com/mrdoob/three.js/blob/master/src/math/Sphere.js#L10) which means the brushMesh is inadvertently modified when applying the matrix transformation to the sphere. This is probably the safest way to do it:

```js
const sphere = new THREE.Sphere();
sphere.center.copy( brushMesh.position );
sphere.radius = params.size;
sphere.applyMatrix4( inverseMatrix );
```

> AND it seems to even work with non-uniform scaling + rotation! 👀 (three 0.122.0)

So non uniform scaling won't _completely_ break things but the intersections won't be exactly correct. Maybe more intuitively: If the bvh mesh is scaled narrow wide in one dimension the then the scale of the sphere in that local frame should be extra wide in that dimension to accommodate. However the [Sphere](https://threejs.org/docs/#api/en/math/Sphere) class only has a single value for the radius which means a non uniform radius sphere can't be represented. Depending on your use case that may be acceptable. These caveats in non uniform scaled cases for shape intersections are probably worth noting in the docs, as well.

> Sure, I'll be glad to! 🙂

Awesome! I appreciate it.

**Comment by arpu** [comment]
@vatro  can you share your drawing sample?

**Comment by gkjohnson** [comment]
@vatro I've updated the example to use the approach I suggested and included a rotation flag to verify it works:

https://gkjohnson.github.io/three-mesh-bvh/example/bundle/collectTriangles.html

I'll close this but feel free to open another issue if you run into anything else! And I'm with @arpu -- if you have a demo how your app I'd love to see it!

**Comment by vatro** [comment]
> @vatro I've updated the example to use the approach I suggested and included a rotation flag to verify it works:
https://gkjohnson.github.io/three-mesh-bvh/example/bundle/collectTriangles.html

@gkjohnson cool! 👍

> And I'm with @arpu -- if you have a demo how your app I'd love to see it!

@gkjohnson @arpu I initially just did some changes to the 'collectTriangles' example, so it should be pretty similar to @gkjohnson's updated example. I'm using **three-mesh-bvh** in **svelthree** and this technique especially for one of the available XRHand-touch-detection methods, so it will be integrated there, see [svelthree/src/utils/XRHandTouchSphereExt.ts in the 'webxr-vr-hand-tracking' branch](https://github.com/vatro/svelthree/blob/0d5a789109bdd81e70c6757c13f7dcf0f268c6e0/src/utils/XRHandTouchSphereExt.ts#L240-L335) --> it's still WIP (still 'my' implementation using applyMatrix4 on the box and triangles) + needs polish (currently giving my best to push the next release before 2021).

**Comment by gkjohnson** [comment]
Great! Looking forward to it. Also note that regarding this callback in your code:

https://github.com/vatro/svelthree/blob/0d5a789109bdd81e70c6757c13f7dcf0f268c6e0/src/utils/XRHandTouchSphereExt.ts#L270-L282

The `tri` variable is not new instance every time and should not be retained. It is a shared instance that is modified before every callback so you should create a copy instead.
