### ISSUE TITLE
tag-update

### ISSUE THREAD

**Issue by obrhaberer** [gkjohnson/three-mesh-bvh#157]
Hello,

it's quite a long time since you updated the tag so npm would install the latest changes or should one use the build-scripts inside the repo-master-branch?

Btw. Good work!

**Comment by gkjohnson** [comment]
Hello! Is there something specific you're expecting to be published? There haven't been significant updates to the codebase in awhile aside from a couple experiments so there hasn't been a reason to update npm.

This last weekend the project has been updated to remove deprecation warnings for three.js v0.123.0 which I will be looking into publishing in the next week or so.

**Comment by obrhaberer** [comment]
Yes especially that was the part I was looking for.

**Comment by gkjohnson** [comment]
Okay please allow for some time -- v0.123.0 that introduced the warnings was released less than a week ago. I will try to have it published soon.

**Comment by gkjohnson** [comment]
Just published the fix in v0.3.0 to npm.
