### ISSUE TITLE
THREE.Matrix4: .getInverse() has been removed. Use matrixInv.copy( matrix ).invert(); instead.

### ISSUE THREAD

**Issue by obsius** [gkjohnson/three-mesh-bvh#158]
Not broken, but the newest version of THREE (r123) has deprecated the getInverse function and getting lots of these warnings now.

**Comment by gkjohnson** [comment]
Yeah this has been fixed with #156. I plan to publish a new version this week. Thanks!

**Comment by gkjohnson** [comment]
Just published v0.3.0

**Comment by obsius** [comment]
Awesome.  Thanks for putting this library together and keeping it up to date.  Much appreciated and great work!
