### ISSUE TITLE
Add option for casting against leaf nodes only

### ISSUE THREAD

**Issue by gkjohnson** [gkjohnson/three-mesh-bvh#16]
This would skip triangle casts for an efficiency boost and allow for a shallower tree while still support tight raycast bounds.

**Comment by gkjohnson** [comment]
@mquander 

Do you feel this be an option on the bounds tree constructor or the raycaster, a la `firstHitOnly` so it can be more easily used globally?

#### Constructor Option
```
geometry.computeBoundsTree({ intersectLeafNodesOnly: true });

// ...

geometry.intersectLeafNodesOnly = false;
```

#### Raycaster Option
```
raycaster.intersectLeafNodesOnly = true;
raycaster.intersectObjects( scene );
```

I'm thinking both options could be available and if the raycaster option is set to `true` then it overrides the setting on the geometry bounds tree. The same thing could be added for `firstHitOnly` so it's available as a constructor option, as well.

**Comment by gkjohnson** [comment]
The default return value for a raycast hit [includes the following values](https://threejs.org/docs/#api/en/core/Raycaster.intersectObject) which won't all be available on a leaf node hit:

```js
{
  distance,
  point,
  face,
  faceIndex,
  object,
  uv
}
```

I'm imagining `face`, `faceIndex`, and `uv` all being set to `null` in the case of a leaf node hit. Maybe an extra boolean value of `leafNodeHit` or reference to the hit tree node can be included to indicate that triangles were not checked.

**Comment by gkjohnson** [comment]
Lastly I'm expecting that the behavior when `Raycaster.firstHitOnly = false` is to return the hits on all leaf nodes that intersect the ray. I'm not sure if there's a better option.

**Comment by mquander** [comment]
It seems to me like an option on the bounds tree to stop at leaf nodes and an option on the raycaster to only get the first intersection are independently useful and reasonable:

1. `computeTruncatedBoundsTree` + `firstHitOnly` = cheap construction, cheap raycast, get closest leaf node volume intersected
2. `computeTruncatedBoundsTree` + `!firstHitOnly` = cheap construction, more expensive raycast, get all leaf node volumes intersected
3. `computeFullBoundsTree` + `firstHitOnly` = same as in current implementation
4. `computeFullBoundsTree` + `!firstHitOnly` = same as in current implementation

**Comment by gkjohnson** [comment]
I agree there should be two different flags -- sorry I was unclear. My question was about whether or not there should be an "intersectLeafNodesOnly" flag on both the `raycaster` _and_ in the BVH constructor.

The flag on the BVH would mean that _only_ that BVH would stop checking at the leafs. If it was set on the raycaster then the raycast would stop at the leaf on every bounds tree being cast against, like a global override. I think the flag in the constructor options is generally more flexible and has more utility so I vote for that until there's a need otherwise.

**Comment by mquander** [comment]
Tree construction and raycasting got way faster and more memory-efficient since we wrote this, and we think it can get even better, so I'm not sure it seems like a high priority anymore.
