### ISSUE TITLE
Suggestion: Add lasso selection example

### ISSUE THREAD

**Issue by gkjohnson** [gkjohnson/three-mesh-bvh#166]
See discussion in #109

**Options**

- Check centroid vs check if any part of the triangle has been intersected.
- "Live" highlighting vs only selecting when releasing.
- Option to early out on single triangle selection to select a whole model precisely.
- Square selection vs lasso selection.

**Comment by gkjohnson** [comment]
Related to #104, #84

**Comment by gkjohnson** [comment]
### Notes

#### Creating and drawing the lasso

- Push points onto an array
- If the line between the new point and the previous point are nearly parallel then just replace the previous point.
- If the mouse hasn't moved outside of some threshold then don't add a point.
- Draw the lasso with a flat `Line` mesh parented to the camera.

#### Detecting centroid selection

- Project point in to screen space. If it's behind the camera near clip then ignore it.
- Check if the point is within the lasso
  - Check the right direction intersection with each lasso line
    - early out if the point is above or below the line
    - early out if the point is to the left or right of both line points
    - otherwise do proper line intersection

#### Detecting triangle selection
- Project all points into screen space.
  - If one point is in front and one behind then clip the segment at the near clip position and create a fourth segment connecting the clipped section.
- Check the right direction intersection for each point with each lasso line
- Early out if two points have a different number of crossings (intersected)
- Check line line intersection for each line in the lasso and edge in the clipped triangle
  - Early out if one intersects
  - Early out on line check if both segment points are completely above or below or left or right of the of the lasso segment points.

**Comment by gkjohnson** [comment]
@brupelo I've created a lasso selection demo here:

https://gkjohnson.github.io/three-mesh-bvh/example/bundle/selection.html

You can toggle the ability to use the bounds tree and between checking for any intersection with a triangle vs just containing the triangle centroid for selection. The time to compute the selection is in the bottom left.

The perf improvement for centroid isn't so huge but when checking for any triangle intersection the improvement can be between 5-50 times for the general case on my machine:

![image](https://user-images.githubusercontent.com/734200/103044895-36cf3880-4537-11eb-8262-8cbc068f7945.png)
 
Of course worst cases like the following see little to no improvement (even degraded performance) compared to not using the bounds tree:

![image](https://user-images.githubusercontent.com/734200/103044976-844ba580-4537-11eb-9252-71d131b8a8f0.png)

There are some other improvements that could be made and triangles that are behind / intersecting the camera near plane are not handled correctly but it's a first pass at what making a per-triangle lasso selection.

**Comment by brupelo** [comment]
@gkjohnson Sorry for not replying before... I wanted to allocate the time to read the code and test out this one properly to give you some feedback, hopefully next weekend I'll be able to. In any case, my first impression after playing a little bit is you've coded something pretty amazing here :O. Why am I telling you this? Cos you won't see many lasso features like this in all github, which means the feature is far away of being trivial... so yeah, hats off!

Dumb question, is it still WIP or you've already pushed it to the repo?

**Comment by gkjohnson** [comment]
Thanks!

> is it still WIP or you've already pushed it to the repo?

It's pushed to the repo but it's just an example of what you can achieve with the BVH the library provides. The core lasso selection happens [here](https://github.com/gkjohnson/three-mesh-bvh/blob/master/example/selection.js#L414). And it's a work in progress as much as anything in the project is. If I think of a way to improve it I might do so when I have time. There are still improvements that could be made but that's what I came up with for the moment. And like I said it doesn't handle the case where the camera clips through triangles or is inside the BVH bounds properly so it's not perfect. In practice depending on your use case you could probably make different assumptions that improve the behavior / performance or not even need a bounds tree at all.

Here's the high level algorithm once you have a static triangle BVH:

**Traversing Bounds**

1. Project all 8 points of the bounds to screen space and generate a convex hull from bounds.
2. Filter the list of all lasso segments down to just those to the right of the projected hull shape or those that could intersect it. If not the root bounds then start with the pre filtered segments from the parent bounds rather than the full set of lasso segments.
3. If one point from the lasso segments is inside the convex hull shape then the hull intersects the lasso and traversal should continue.
4. Check the amount of crossings using the [line crossing algorithm](https://en.wikipedia.org/wiki/Bentley%E2%80%93Ottmann_algorithm) for each point on the hull. If they differ then the bounds intersects the lasso and traversal should continue.
5. Check if any hull line segment crosses a lasso line segment. If they do then the bounds intersects the lasso and traversal should continue.
6. If there are no intersections and the amount of crossings was odd then the bounds is entirely contained by the lasso and you can assume all leaf triangles under that parent bound are contained by the lasso. Otherwise the lasso was not intersected and traversal should stop.

**Checking Triangle Intersection**

1.  Project triangle vertices and segments to screen space.
2. Check the amount of crossings per vertex and if they differ then the triangle intersects the lasso shape.
3. Check the if any of the triangle segments intersect the filtered parent bound lasso segments. If any intersect then the triangle is intersected.
4. Otherwise the triangle is not intersected.
