### ISSUE TITLE
Unable to initialize computeBoundsTree and  disposeBoundsTree into BufferGeometry.prototype

### ISSUE THREAD

**Issue by ibrahimunal** [gkjohnson/three-mesh-bvh#192]
I try to implement the [triangle painting demo](https://gkjohnson.github.io/three-mesh-bvh/example/bundle/collectTriangles.html) from this [source-code](https://github.com/gkjohnson/three-mesh-bvh/blob/master/example/collectTriangles.js) I impelemented this line of code into my imports 

`import { acceleratedRaycast, computeBoundsTree, disposeBoundsTree, CONTAINED, INTERSECTED, NOT_INTERSECTED } from '../../../three-src/index.js';` 
 Even though acceleratedRaycast function is defined and imported succesfully computeBoundsTree and  disposeBoundsTree functions are throws a syntax error which say "Property 'computeBoundsTree' does not exist on type 'BufferGeometry'. " 

![image](https://user-images.githubusercontent.com/36535542/108859571-65809280-75fe-11eb-97b6-7fe572508d2a.png)

I know it's weird to share screenshot of the code but wanted to clarify the issue.

**Comment by gkjohnson** [comment]
This looks like a typescript issue warning you that you're setting a property on the `BufferGeometry` prototype that does not exist on the original object. Unfortunately I'm not a typescript expert so I don't have any suggestions beyond disabling the typescript warnings on those lines.

The docs in the README show a few different ways to use the library but the most convenient ways involve setting new custom fields on BufferGeometry which I suspect Typescript will complain about. If you have ideas on improving things I'm open to suggestions!

**Comment by ibrahimunal** [comment]
Yeah, because I'm trying to implement it into angular project and the issue is about TS part. I'm unable to use  computeBoundsTree and disposeBoundsTree since those functions does not exist as TS format in three js library. That is why it throws an error. Is it possible that you can convert these into TS version also. If not, does the computeBoundingBox or computeBoundingSphere function which are provided by three js library give the approximate result?

**Comment by gkjohnson** [comment]
> Is it possible that you can convert these into TS version also.

This project is not in Typescript and neither is three.js (though there are typescript declaration files). There's nothing I can do to fix this in javascript. You'll have to look into the right way to handle this in your TS project. I would look up how to modify the prototype of a class in Typescript. If you'd like TS declration .d.ts files in this project I'm open to contributions for that.

> If not, does the computeBoundingBox or computeBoundingSphere function which are provided by three js library give the approximate result?

No the bounding boxes and spheres built in to three.js will not afford the same performance and do not provide the same types of spherical spatial queries needed to detect all triangles that intersect a sphere in order to color them.

**Comment by ibrahimunal** [comment]
I'm able to add basic string prototypes into my project and these are work fine but as I try to implement computeBoundsTree function I come up with the same issue. I'd really appreciate if u could manage to convert it into TS format and also I'll try to work on it. This is where I've come so for btw. computeBoundsTree throws "Property 'computeBoundsTree' does not exist on type 'BufferGeometry'.ts(2339)" error.



```
    declare global { 
        interface BufferGeometry {
            computeBoundsTree(options: any): MeshBVH;
        }
        }
      
    BufferGeometry.prototype.computeBoundsTree = function(options) {
        
            this.boundsTree = new MeshBVH(this, options);
            return this.boundsTree;
            
        }
```

**Comment by ibrahimunal** [comment]
I finally managed to add functions into BufferGeometry prototype into my angular project. There is no need to create an external ts file and add it into the app.module.ts. Three js package which install through npm already has BufferGeometry.js and BufferGeometry.d.ts file . All I need to do was declaring diposeBoundsTree function in BufferGeometryd.ts file as  `disposeBoundsTree():void;` and import the original function which is 
```
function computeBoundsTree() {
	this.boundsTree = new MeshBVH(this, options);
	return this.boundsTree;
}
``` 
into the BufferGeometry.js
after that  I'm able to insert that function into BufferGeometry.prototype
