### ISSUE TITLE
Chore: Update lint rules to match newer three styles

### ISSUE THREAD

**Issue by dbuck** [gkjohnson/three-mesh-bvh#209]
I was looking to add an example for my own learning, and was thinking that a pooled worker example might be generally helpful for others also. Alas I'm too spoiled with async/await in my own testbed, so I didn't finish setting it up in yours ;)

It looks like async/await was disallowed by the older mdcs tslint rules, they've since moved on to [versions with es2020 support](https://github.com/zz85/mrdoobapproves/pull/73) for examples

three is now set up using:
```
    "eslint": "^7.20.0",
    "eslint-config-mdcs": "^5.0.0",
```

Running lint with --fix cleans up the majority of the newly classified errors, leaving some warnings about unused things.

**Comment by gkjohnson** [comment]
Hello! Thanks for the report. I'm happy to take a PR that updates the lint rules and fixes the errors if you're interested.

And providing a demo of how to pool `GenerateMeshBVHWorkers` and process multiple geometries at once isn't a bad idea. I'll be interested to see your demo!

**Comment by dbuck** [comment]
Actually, now that I glance at the diff, it looks like the 'fixes' were mostly newlines, I'll push something up for you to take a look later on, Cheers.
