### ISSUE TITLE
Possibly add support for InstancedMesh

### ISSUE THREAD

**Issue by gkjohnson** [gkjohnson/three-mesh-bvh#237]
Instanced mesh could possibly be supported by bookkeeping each instance as a point in a BVH and raycasting against each point assuming it has the bounding sphere radius of the instanced object. It gets complicated if each instance has a significantly different scale. You'd have to assume the largest scale when raycasting against all objects. This may be starting to overextend on what this BVH implementation is capable of, though, considering it's made just for geometry. Another type of spatial index may be required for this.

**Comment by Ben-Mack** [comment]
+1 for this. 
Looking forward for InstancedMesh support.
I don't really understand technical details of BVH, but can we just use the same BVH structure and transform its matrix to check intersecting of each instance? Maybe it'll help on perf and simplifying the implementation.

**Comment by gkjohnson** [comment]
> I don't really understand technical details of BVH, but can we just use the same BVH structure and transform its matrix to check intersecting of each instance? Maybe it'll help on perf and simplifying the implementation.

As far as I understand this should already work. Have you tried it? Three.js' InstancedMesh.raycast function [ultimately calls Mesh.raycast](https://github.com/mrdoob/three.js/blob/e8877dfb85ae017f53ef8d91237909bc162f524b/src/objects/InstancedMesh.js#L75) so if `Mesh.prototype.raycast` has been overridden with the accelerated version from this project then it should "just work" but it's worth verifying.

The implementation referenced in this issue was just an idea for repurposing the existing BVH implementation to quickly cull the instances that need to be checked (as opposed to just improving the triangle intersection phase). Currently `InstancedMesh.raycast` checks against the bounds of every instance before checking the triangles and there may be some benefit to use a spatial index to speed that part up. But generally I feel that a more general spatial index implementation would be better suited to a task like that so I don't really expect this issue to go anywhere for a bit.

**Comment by gkjohnson** [comment]
Closing this because I think a different type of data structure would be best for instanced meshes. @Ben-Mack if you find that the BVH doesn't already work for improving performance for raycasting against individual instances feel free to open a new issue.
