### ISSUE TITLE
Reduce THREE code duplication

### ISSUE THREAD

**Issue by gkjohnson** [gkjohnson/three-mesh-bvh#25]
Some of the code in IntersectionUtils and GeometryUtils is copied from THREE js because its not otherwise exposed. If possible this copied code should be removed or at least reduced.

TODO: Document which functions are copied

**Comment by mquander** [comment]
Since our code is becoming slightly more specialized (e.g. it assumes a `BufferGeometry` with an index) and performance is at a premium, it seems like it's becoming less likely that it will make sense to reuse three.js code for this directly.

**Comment by gkjohnson** [comment]
Yeah we can probably make some of those functions a bit faster if we commit to using the BufferGeometry attributes. My concern is keeping up with any changes to the returned raycast results object that THREE implements. If we can use the built in functions then ideally that format would just fall out without any changes here.

Realistically that will probably not change very often, though, so maybe it's not worth worrying about.
