### ISSUE TITLE
CharacterMovement Example: Prevent character from sliding down stairs, ramps

### ISSUE THREAD

**Issue by gkjohnson** [gkjohnson/three-mesh-bvh#251]
Related to #247 

The capsule collider being adjusted by all triangles on the stairs results in the character being pushed to the side, then sunk by gravity, then pushed to the side, etc. It results in the character slowly sliding down the stairs. An improvement would be to not slide down corners at all or sliding more quickly so it's not as visually intrusive. The sliding behavior would likely also happen down ramps.

- Prioritize more horizontal triangle adjustments over vertical ones to the character moves up first before being moved horizontally.
- Adjust the "is on ground" logic so the rate at which the character will fall down to the next stair is increased.

**Comment by makc** [comment]
you have this: https://github.com/gkjohnson/three-mesh-bvh/blob/master/example/characterMovement.js#L420-L435 then maybe you should only do `player.position.copy( newPosition );` inside of `if ( ! playerIsOnGround ) {` ?

**Comment by gkjohnson** [comment]
> then maybe you should only do `player.position.copy( newPosition );` inside of `if ( ! playerIsOnGround ) {` ?

Thanks for taking a look @makc! Unfortunately if you only apply the new adjusted position from the collisions if the player is seen as "on the ground" then the player will start to sink through the floor because the collision adjustment from the ground isn't applied.

@vin-ni I took a bit of a look at it and fixed the sliding issue in #252. I've updated the example build on master so take a look and see if that fixed it for you.

**Comment by vin-ni** [comment]
Thanks, I'll take a look.

**Comment by gkjohnson** [comment]
Gonna close this for now -- feel free to ping or open a new issue if there's still an issue @vin-ni!

**Comment by vin-ni** [comment]
Works for now! Thank you!
