### ISSUE TITLE
[Idea Discussion]  using bvh for cannon-es trimesh (octree) Implementation

### ISSUE THREAD

**Issue by arpu** [gkjohnson/three-mesh-bvh#253]
Hey,

cannon-es has a very good octree implementation for mesh collision ( using Trimesh) 
https://github.com/pmndrs/cannon-es/blob/master/src/shapes/Trimesh.ts

would it make sense to try bvh in this field?

**Comment by gkjohnson** [comment]
Hey @arpu! Can you elaborate on what you mean? What are you looking for / trying to do?

Are you asking if three-mesh-bvh can be used to detect mesh intersections?

**Comment by arpu** [comment]
Hey yes, idea to speed up the octree?

**Comment by gkjohnson** [comment]
I'm unfamiliar with the details of cannon-es and unfortunately don't have the time to investigate performance improvements for another package. If you have a specific implementation question I'm happy to answer but you should open an issue in cannon-es if you'd like them to improve performance of the octree or look into a different type of spatial data structure to represent the trimesh and you can ping me there if needed.
