### ISSUE TITLE
Can we calculate 3D model wall thickness using this library

### ISSUE THREAD

**Issue by SrinivasPrabhu794** [gkjohnson/three-mesh-bvh#254]
Hi @gkjohnson 

I have a problem where I need to calculate the the wall thickness of a 3D model for printing.

Is there a way I can use your library/ray casting to do the same?

Any help would be invaluable

Thanks!

Regards
Srinivas

**Comment by gkjohnson** [comment]
Hello! If you just want to measure the distance between a front back face along a ray direction you can use raycasting to do that. Of course you don't need this package to perform that kind of raycasting but it will help speed it up.

Beyond that I'm not familiar with the types of geometry processing that are needed for 3d model printing. I'd try asking on the three.js forum.
