### ISSUE TITLE
How to retrieve the triangle index from the intersectsTriangle callback arguments in shapecast? 

### ISSUE THREAD

**Issue by Mathias-Fuchs** [gkjohnson/three-mesh-bvh#289]
I'm basically using the point cloud example. It recommends to call the shapecast function on a boundsTree and provide an intersectsTriangle callback
```typescript
 x.boundsTree.shapecast(
      buffergeom,
        {
              boundsTraverseOrder: box => box.distanceToPoint(this.raycaster.ray.origin),
              intersectsBounds: (box, isLeaf, score) => {
                        if (score > closestDistance) return NOT_INTERSECTED;
                        box.expandByScalar(threshold);
                        return this.raycaster.ray.intersectsBox(box) ? INTERSECTED : NOT_INTERSECTED;
                    },
             intersectsTriangle: (triangle, index) => {
// HERE, index is not the index of the triangle!
// how do I get the correct index of the triangle?
                }
        }
);
```
It all works great and as expected! However, the index that is passed to my callback is not the index of the triangle that is passed to the callback! I need the index of the triangle, not just its three corner coordinates triangle.a, triangle.b, triangle.c.
Any help greatly appreciated.

**Comment by gkjohnson** [comment]
Hey @Mathias-Fuchs! The `index` argument of the `intersectsTriangle` callback should indeed give you the index of the triangle in the index buffer but you have to multiply it to get the three vertex indices. So the the indices of the vertices making up the triangle would be the following:

```
3 * index + 0
3 * index + 1
3 * index + 2
```

Hopefully that makes sense! It looks like the docs might be out of date / could be more clear. If you'd like to make a PR to help improve them I'd appreciate it!

**Comment by gkjohnson** [comment]
I'm assuming this has been answered -- feel free to open a new issue otherwise!
