### ISSUE TITLE
Consider making ThreeIntersectionUtilities.checkIntersection() configurable

### ISSUE THREAD

**Issue by yomboprime** [gkjohnson/three-mesh-bvh#318]
This issue happens to me because I'm making particular things. But it could lead to general errors that have not been detected yet. Also, this is more an issue of Three.js rather than Three-mesh-bvh.

In short, rays are sneaking through adjacent triangles because I'm deliberately pointing the rays to the edge shared between them.

Let me explain: I'm sampling lots (thousands) of points of interest around a mesh. For each point I'm getting the closest point in the mesh surface with ```MeshBVH.closestPointToPoint()```. This works great. Then I shoot a ray from the point of interest to the closest point, just to obtain the UV coordinates. This ray sometimes sneaks through two triangles (depending on numerical errors). It happens when the POI is located in the region between two triangles as in the following image, where the closest point is always on the edge between the two tris:

![imagen](https://user-images.githubusercontent.com/2453652/131317923-06f8fa5c-435a-429b-ae12-cd3dba79c3c0.png)

Unexpectedly, for some POIs the rays are hitting none of the two triangles. The reason is just as if there was Z-fighting, because I've pointed the ray right to the edge.

So, to solve this issue, I've replaced (in a hacky way) the calls to ```Ray.intersectTriangle()``` in ```ThreeIntersectionUtilities.checkIntersection()``` to call my own ray-triangle intersection function. This function is more intuitive to read, and although is probably not as performant as Three.js's one (but not by much), it has the advantage of having some hysteresis threshold value. The threshold is tiny (10⁻¹² units), but is sufficient to solve the issue completely. I copied this function from elsewhere years ago, and the threshold is there to solve this precise issue when raycasting meshes. Keep in mind this only works with ```MeshBVH.raycastFirst()```, as redundant intersections could be returned for ```MeshBVH.raycast()```

So my question is, could it be made configurable wich final ray-triangle intersection function is used in Three-mesh-bvh?

Here is the ray-intersection function I've adapted:

```javascript
const intersectionThreshold = 1.0E-12;

const temp_edge1 = new Vector3();
const temp_edge2 = new Vector3();
const temp_normal = new Vector3();

const temp_dif0 = new Vector3();
const temp_dif1 = new Vector3();

function intersectRayTriangle( ray, a, b, c, backfaceCulling, target ) {

	// Taken from the engine Nebula 2 device (http://nebuladevice.cubik.org/), which in turn took it from
	// Magic Software (http://www.cs.unc.edu/~eberly)

	temp_edge1.subVectors( b, a );
	temp_edge2.subVectors( c, a );
	temp_normal.crossVectors( temp_edge1, temp_edge2 ).normalize();

	// Compute the triangle plane equation, Dot( normal, X - v0 ) = 0
	// If the angle between ray and plane is small, they are parallel, so return null.
	const denominator = temp_normal.dot( ray.direction );
	if ( backfaceCulling ) {

		if ( denominator >= - intersectionThreshold ) return null;

	}
	else if ( Math.abs( denominator ) < intersectionThreshold ) return null;

	// Compute ray parameter (t) for the intersection. To do this, substitute and clear in the plane equation:
	// Dot( normal, b - v0 ) + t * Dot( normal, m )
	temp_dif0.subVectors( ray.origin, a );
	const t = - temp_normal.dot( temp_dif0 ) / denominator;
	if ( t < intersectionThreshold ) {
		return null;
	}

	// Obtain the difference between intersection point and vertex 0 of triangle
	temp_dif1.copy( ray.direction ).multiplyScalar( t );
	temp_dif1.add( temp_dif0 );

	// Computes whether intersection point lies in the triangle. From equation dif1 = s0 * e0 + s1 * e1, find s0 and s1
	const e00 = temp_edge1.dot( temp_edge1 );
	const e01 = temp_edge1.dot( temp_edge2 );
	const e11 = temp_edge2.dot( temp_edge2 );
	const det = Math.abs( e00 * e11 - e01 * e01 );
	const r0 = temp_edge1.dot( temp_dif1 );
	const r1 = temp_edge2.dot( temp_dif1 );

	const s0 = e11 * r0 - e01 * r1;
	const s1 = e00 * r1 - e01 * r0;

	if ( s0 >= - intersectionThreshold && s1 >= - intersectionThreshold && ( s0 + s1 ) <= det + intersectionThreshold ) {

		// Intersection point lies in the triangle
		return target.addVectors( a, temp_dif1 );

	}

	// Intersection point lies outside the triangle
	return null;

}

```

**Comment by yomboprime** [comment]
Now that I think of it, perhaps it would suffice to do this?
```Ray.prototype.intersectTriangle = myFunction;```

The problem is that I need the non-bvh-accelerated, dynamic raycasting also in my program.

**Comment by gkjohnson** [comment]
Thanks for the detailed description of the issue! I'm thinking this issue might belong in the three.js repo since this projects goal wrt raycasts is to just perform the same thing faster and as you mentioned the problems plague three.js raycasting, as well. But generally I think this type of problem is rare since it's uncommon / difficult to position a ray directly on an edge so I think your work around of setting `intersectTriangle` should be sufficient.
 
Regarding the reason why you're raycasting at edges (get the UV of the closest found point) it seems like the results of `closestPointToPoint` could be improved to include more face information like the raycast functions do rendering the additional raycast unnecessary. Something like the following could be returned:

```js
// return value from `closestPointToPoint`
{
  point: Vector3,
  distance: Number,
  face: {
    a, b, c, materialIndex, normal,
  },
  uv: Vector2
}
```

Then you wouldn't need to raycast because you'd already have the UV value. The same could be done for the `closestPointToGeometry` function. My time is occupied with other interests on this project right at this moment but if you'd like to contribute that change I'd be happy to take a PR but keep in mind it might be a bit before I can wrap up what I want to for a v0.5.0 release. Or in the short term you could implement your own `closestPointToPoint` function that returns the UV considering it just uses `shapecast` under the hood:

https://github.com/gkjohnson/three-mesh-bvh/blob/1dcb2310a08e46131c51f0d74325a10746ddb1e4/src/core/MeshBVH.js#L888-L948

On a final note what you're working on sounds very unique -- if you're able to share anything related to it publicly I'd be interested to see at some point!

**Comment by yomboprime** [comment]
Thanks for the detailed response!

Following your advice I've tried to implement my own ```closestPointToPoint()``` function, but unfortunately the ```tri``` parameter of the ```intersectsTriangle()``` shapeCast callback doesn't contain the triangle indices, which I need to calculate the UV with ```Triangle.getUV()```. Do you see a solution for this?

Thanks for your interest in my project. I'm going to publish it with MIT license soon 😊

**Comment by gkjohnson** [comment]
> unfortunately the tri parameter of the intersectsTriangle() shapeCast callback doesn't contain the triangle indices

The `intersectsTriangle` function takes a `triangleIndex` which can be used to compute the vertex indices like so:

```js
const i0 = triangleIndex * 3 + 0;
const i1 = triangleIndex * 3 + 1;
const i2 = triangleIndex * 3 + 2;
```

These indices can be used as accessors to the `index` buffer attribute to in turn get the position attribute buffer indices. 

It looks like the docs were a little out of date / unclear but I've just updated them to clarify a little bit (see [shapecast docs](
https://github.com/gkjohnson/three-mesh-bvh#shapecast)). I'll have to do another pass at them soon to make sure everything is correct but if you have any feedback on how to improve the shapecast docs I'm all ears -- that's the most complicated one, I think.

**Comment by yomboprime** [comment]
Thanks! It works. By saving the extra ray I've gained roughly 30% computing time.

I've re-read the cited docs and I find them right.

I can make a PR with the extra return info in ```closestPointToPoint()```. Although I've not seen it in the contributing guidelines, I guess one must build with ```npm build``` after the changes?

**Comment by gkjohnson** [comment]
Awesome! No need to commit builds -- I run that before making a release.

**Comment by yomboprime** [comment]
I'm sorry to be dummy, but when I do ```npm install``` I get high vulnerabilities errors:

![imagen](https://user-images.githubusercontent.com/2453652/131585486-580aae0e-2daf-464a-ab91-9eef73dd7862.png)

**Comment by gkjohnson** [comment]
Depending on what your question is those shouldn't be an issue considering these are for dev tools but I've gone ahead and run `npm audit fix` to fix the ones it can but for parcel-bundler I've already installed the latest version which has dependencies that are marked as vulnerabilities and `dat.gui` doesn't have a newer version to upgrade to.

Generally I think these RegEx DDOS high vulnerability warnings (which is all it seems to be here) are a bit blown out of proportion especially for packages intended to be run client-side. Effectively all it means is that a user can pass a string that will cause the specified regex to run for extremely long times which would be bad if you're processing user input data on a server but not a huge deal if it's running on a client (may crash a users webpage or take down dev server). But again the string has to be maliciously constructed to cause the problem which won't be a problem in dev and what user would want to do that to themselves. Three.js actually had one of these earlier this year (see [this issue](https://github.com/mrdoob/three.js/issues/21132)).

I try to keep up to date on packages I'm actively maintaining but sometimes they get behind or can't upgrade.

If you'd like to run tests you can do so by running `npm run test` and for examples just run `npm start` and visit the examples at `localhost:9080/example/dev-bundle/*.html`. Tests will likely break if change the return value of that function so if you want to just paste the modified function code here or submit a basic PR with just the function changes I can take a look and integrate it when I have the time.

**Comment by yomboprime** [comment]
Thanks, I've made the PR.
