### ISSUE TITLE
BVHCast function assumes two bvh share the same geometry

### ISSUE THREAD

**Issue by minitoine** [gkjohnson/three-mesh-bvh#368]
Hi,

I am working on a render engine that needs to compute **all** the line intersections between two geometries' faces.
Looking from the code, the bvhcast function seems to be the perfect match. I also looked at your example [EdgeIntersect.js ](https://gkjohnson.github.io/three-mesh-bvh/example/bundle/edgeIntersect.html)

The thing is, the bvh cast function seems to assume the two bvh share the same goemetry and thus, [triangle1](https://github.com/gkjohnson/three-mesh-bvh/blob/838061974481fb822d8734eb7ff767ad545eff6d/src/core/MeshBVH.js#L611) and [triangle2](https://github.com/gkjohnson/three-mesh-bvh/blob/838061974481fb822d8734eb7ff767ad545eff6d/src/core/MeshBVH.js#L619) are gathered from the same index and position buffers.

It might be a good idea to consider that the otherBvh param is built with a different geometry, which shouldn't change a lot of things in the code.

I can propose a new PR if needed. But I guess the problem is probably not as simple as it seems.

**Comment by gkjohnson** [comment]
Oh yeesh yes that's definitely a bug! Thanks for digging into it. If you could make a PR that would be great -- and if possible adding a test would be nice, as well -- and we can get it merged and published. I think it's a relatively simple fix. The `triangle2` field should be set to the triangle from the `otherBVH.geometry` and `triangle` should be set to the triangle from `this.geometry` and I think that's all that needs to be done

Thanks!

**Comment by gkjohnson** [comment]
Fixed in #369 and published in v0.5.3!

Thanks again for the report and fix @minitoine. If you're able to share the project you're using three-mesh-bvh for I'd love to see!
