### ISSUE TITLE
Rename and document `maxLeafNodes` option

### ISSUE THREAD

**Issue by gkjohnson** [gkjohnson/three-mesh-bvh#37]

**Comment by mquander** [comment]
I agree. How about `maxLeafTris`?

**Comment by gkjohnson** [comment]
Sounds fine to me!

**Comment by mquander** [comment]
This was renamed in https://github.com/gkjohnson/three-mesh-bvh/commit/933258896d791d02698d9ffa7e642f34a75d7cab.
