### ISSUE TITLE
Player gets stuck inside the floor

### ISSUE THREAD

**Issue by a-saq** [gkjohnson/three-mesh-bvh#370]
Hello, 

I have multiple terrains with different Y positions, between -1 and 1 and an initial player Y position of 0.

When the player overlaps with the terrain, Instead of correcting the position and put the player above the floor, it gets stuck on the floor instead.

I managed to reproduce that behavior in the characterMovement example by repositioning the dungeon `gltfScene.position.y -= 1` 

![image](https://user-images.githubusercontent.com/34965936/147254999-8c9244d6-02bc-4955-9b1e-5d9ac8169711.png)

**Comment by gkjohnson** [comment]
The demo is designed to to have the capsule start outside the geometry so I wouldn't expect this to work. You'll have to position the player mesh appropriately.
