### ISSUE TITLE
latest threejs master removed 'RGBFormat' r137dev

### ISSUE THREAD

**Issue by arpu** [gkjohnson/three-mesh-bvh#372]
export 'RGBFormat' (imported as 'RGBFormat') was not found in 'three'
 i think this can be simple removed ( using RGBAFormat)

**Comment by gkjohnson** [comment]
Great! Thanks for the heads up. Would you like to try making a PR that resolves the issue for r137?

**Comment by arpu** [comment]
Hey, first try on this ->


https://github.com/gkjohnson/three-mesh-bvh/pull/374

**Comment by arpu** [comment]
looks like there is still a reference in https://github.com/gkjohnson/three-mesh-bvh/blob/master/src/gpu/MeshBVHUniformStruct.js#L5
