### ISSUE TITLE
SeparatingAxisTriangle.intersectsTriangle return line points outside intersecting triangles

### ISSUE THREAD

**Issue by minitoine** [gkjohnson/three-mesh-bvh#382]
Hi,

I think there is a bug in the `intersectsTriangle` function of `SeparatingAxisTriangle` class. ([link](https://github.com/gkjohnson/three-mesh-bvh/blob/fd7704c05a90b3df3ad7a221c0e7e2da94bf10ba/src/math/SeparatingAxisTriangle.js#L125)).

Lines 223 to 268 ([link](https://github.com/gkjohnson/three-mesh-bvh/blob/fd7704c05a90b3df3ad7a221c0e7e2da94bf10ba/src/math/SeparatingAxisTriangle.js#L223-L268)) , you are looking for 2 edges of each triangle that intersect the other triangle plane, and you use dot product to deduct the output intersection line.
But, there is a possibility that 3 edges of a triangle intersect the other triangle plane, which means the output line points are outside of both the input triangle. (This is the bug i'm facing).

Here is a quick drawing.
![Untitled](https://user-images.githubusercontent.com/6161713/152141198-cd2a4a1c-c901-4d46-8a7c-84c8733b3a83.jpg)

A possible solution:
- Intersect T1 edges on T2 plane and discard points outside T2 
- If we have 2 points we good otherwise
- Intersect T2 edges on T1 plane to find the missing point(s)

I don't really know the cost of testing if a point is inside a triangle.

Edit: 
I think that if you compute all the intersection points (max 6), then only the middle ones can be inside the triangles which could reduce the number of tests to 2 if the number of points is odd.

**Comment by gkjohnson** [comment]
> But, there is a possibility that 3 edges of a triangle intersect the other triangle plane, which means the output line points are outside of both the input triangle.

In this case the triangles are coplanar, right?  And can you clarify your drawing? It does not look like the triangles in your drawing are coplanar. Or am I misunderstanding?

If that's the case then yes the algorithm currently does not support a valid output for intersecting coplanar triangles. If you'd like to add a quick check at the top of the function to check if the triangles are coplanar and handle that as a special case I think that would work. Happy to take a PR with a solution!

Tests for the SeparatingAxisTriangle would also be great.

**Comment by minitoine** [comment]
I used Geogebra to make a more clear drawing. As you can see, triangles are not coplanar (in that cas, intersection needs to be handled in 2D). In some configurations, all edges of a triangles can intersect the other triangle plane (here all edges of T1 intersect T2's plane). So if you're looking in the code for the first 2 edges that intersect, the points you obtain can be outside of both triangles giving a wrong intersection line.

I'm working on an algorithm on my side, but that's a complex stuff as you know it.

<img width="751" alt="Screen Shot 2022-02-02 at 21 55 16" src="https://user-images.githubusercontent.com/6161713/152236008-9f6211c5-f369-42cf-9576-c908a75a19b0.png">

**Comment by gkjohnson** [comment]
I think I'm still missing something. I believe I'm understanding the picture a bit better now and I agree that all three rays defined by the edges of T1 intersect the plane of T2 but I'm not seeing how all the edges (line segments) of T1 intersect the T2 plane. Both points G and H clearly lie on the line segments BC and AC and intersect the plane but line segment AB does _not_ intersect the plane and point I is outside the range of AB.

The [code used to find the edge / plane intersections](https://github.com/gkjohnson/three-mesh-bvh/blob/5aed27762a4e19c5001c0822a3fadd8b90f1ccd8/src/math/SeparatingAxisTriangle.js#L220-L268) uses three.js' `Plane.intersectLine` function which checks for an intersection between a line segment and the plane. That means that the point I in your image would not be accounted for. Could the problem be somewhere else? There could very well be a bug here I'm just not convinced yet that the issue is what you've described. Again unless I'm misunderstanding something which is still very possible 😁.

**Comment by minitoine** [comment]
Indeed, I didn't deeply check the code behind `Plane.intersectLine` and I assumed it considered the line param as an infinite line, which is not the case. So yup, the problem doesn't come from multiple intersection points.

Now, I wonder if the problem comes from the fact you are not testing if you have found the 4 intersections you expect from both planes. The code is actually iterating over edges of a triangle and check intersection with the plane of the other triangle (and vice versa).
If you actually find the 4 intersections, `start` and `end` points of `edge1` and `edge2` are updated, otherwise you are using old values (I agree, theoretically it shouldn't be the case), and so, returning a *wrong* intersection Line.
For complex geometries, you could have a lot of edge cases where mathematical precision fails.

I modified the code directly in my node_modules folder to add 2 counters and check if you find 4 intersections. You'd be surprised the number of times you don't find them.

In that case, shouldn't it be better to return false when the 4 intersections have not been found ?

Again, trying to find a more robust method on my side.. not easy.

**Comment by gkjohnson** [comment]
Can you provide a test case that causes the incorrect result? By the time that code is encountered it should have passed the SAT test meaning they intersect and there should four results from the plane intersections. But looking at that SAT code again it might be incorrect. That function is admittedly not a very well-tested part of the codebase.
