### ISSUE TITLE
worker and geometry groups

### ISSUE THREAD

**Issue by VegarRingdalAibel** [gkjohnson/three-mesh-bvh#392]
Hi

I just tried to replace `geometry.computeBoundsTree()` with the workers, but getting weird results when I try and highlight data by using parts of the index groups in merged geometry.

Its like worker does not take into account groups of merged geometry.
Or maybe I just have messed up something else 😂

**Comment by gkjohnson** [comment]
Hi @VegarRingdalAibel! Thanks for the report. Sounds like a bug. Are you interested in submitting a PR with the fix? I think we just need a change in two places. One here to pass a copy of the BufferGeometry.groups object to the web worker:

https://github.com/gkjohnson/three-mesh-bvh/blob/c42bcbe148bad0bd3e0af240b0e5d0325ba5e348/src/workers/GenerateMeshBVHWorker.js#L93-L103

And one around here to assign the groups to the new geometry object:

https://github.com/gkjohnson/three-mesh-bvh/blob/c42bcbe148bad0bd3e0af240b0e5d0325ba5e348/src/workers/generateAsync.worker.js#L32-L38

**Comment by vegarringdal** [comment]
Did a PR, you can have a look/make edits if you feel something should be changed :-)
