### ISSUE TITLE
Examples: Add an SDF demo

### ISSUE THREAD

**Issue by gkjohnson** [gkjohnson/three-mesh-bvh#411]
Write into 3d textures? Ray marching / volumetric / marching cubes demo?

**Comment by gkjohnson** [comment]
SDF particle physics:
- https://twitter.com/reduzio/status/1312383542530318346?lang=en
- https://spite.github.io/sdf-physics/

**Comment by DennisSmolek** [comment]
So like.. The super mindblowing SDF projects are awesome, 
and it being GPU run is even better, but can the first demo be something really simple?
Like, Generate a SDF for the Standford Bunny and Suzanne and blob them together?

Maybe with a Sphere or Cube to show how to mix in general raymarching?

I'm learning/trying/working on environmental stuff that I'm having a hard enough time resolving how to mix raymarching with the default ThreeJS Scene.

Im guessing it's something similar to @n8programs using multi-pass etc, although the link https://jacco.ompf2.com/2022/05/13/how-to-build-a-bvh-part-6-all-together-now/

Does the BVH & Raymarching together which seems smart, but I'm not sure how different his BVH setup is (I'm a newb)

**Comment by gkjohnson** [comment]
@DennisSmolek - I've added a simple demo showing how to generate and render an SDF from a BVH!

**Comment by DennisSmolek** [comment]
> @DennisSmolek - I've added a simple demo showing how to generate and render an SDF from a BVH!

Very Cool! I'm going to tear through it now!

I'm guessing the layers are on purpose to show its infinite, but it's a little confusing thinking you'll see the "sdf" version of the mesh. 
What's the trick to only show the SDF at model size?

**Comment by gkjohnson** [comment]
What do you mean by "layers"? Do you mean the layer display mode? It shows each layer of the SDF texture (I'd forgotten to push the changes with the grid of 3d texture layers):

![image](https://user-images.githubusercontent.com/734200/201499414-5c130a59-ccfc-476b-8372-30e115a3b8bc.png)

I'll add a little more of a context explanation, as well.

**Comment by DennisSmolek** [comment]
Oh this is a platform issue I think.

on mobile I see this:
![76CB400B-6446-4886-BD48-4F42AA4A2A0D](https://user-images.githubusercontent.com/1397052/201499528-fdd5b7a7-7d20-4aed-ba92-05db7ac69d9f.png)

but on my MacBookPro (M1 Pro 2022)
I’m seeing the image you posted on Twitter

**Comment by gkjohnson** [comment]
Oh hm - that looks like linear filtering isn't supported for 3d textures on your device or something? With nearest filtering the raymarching looks like this:

<img width="740" alt="image" src="https://user-images.githubusercontent.com/734200/201499712-f0fe13ca-c99e-404a-99c5-fb27859623d6.png">

**Comment by DennisSmolek** [comment]
More bad news:

Windows 11 i9 with a 3060. 
Both Chrome and Edge:

<img width="778" alt="Screenshot_20221112_185805" src="https://user-images.githubusercontent.com/1397052/201500562-c9debfa1-6185-45c9-9565-7f2bd73dc454.png">

If I disable gpuGenerationit works as expected after taking forever:
<img width="671" alt="Screenshot_20221112_185735" src="https://user-images.githubusercontent.com/1397052/201500584-8ba677b6-6d7f-4c9c-8d30-01916c944f0a.png">

**Comment by DennisSmolek** [comment]
Update on my Macbook:

Left is Safari, right is Chrome
![Screen Shot 2022-11-12 at 19 05 27](https://user-images.githubusercontent.com/1397052/201500773-5cfffd2e-aee6-4f1c-9cbf-7c29f38a010a.png)

**Comment by gkjohnson** [comment]
Looks like I've got to fix something on my android, as well. But rendering into 3d textures is something rarely done in the web afaict. I wonder if there are hardware or compiler quirks that need to be addressed. I'm kind of surprised Chrome is behaving like that, though.

I probably wont be able to debug some of these, though, since I don't have comparable hardware available.

**Comment by DennisSmolek** [comment]
> But rendering into 3d textures is something rarely done in the web afaict. 

Yeah your setup for this was pretty interesting.
I still need to go through the flow a bit with the generator, material, and rendering.
Most of what I’ve seen is Texture3D slices.

Plus the only SDF serialization I’ve even touched before was messing with Unreals.

> I probably wont be able to debug some of these, though, since I don't have comparable hardware available.

This is something I can help with! Android is the one device I *don’t* have easy access to.

craziest thing is iOS is the most stable/efficient! 🤷‍♂️

Once I understand the problem a bit more I can walk it through.

The windows one is clearly a GPU thing because the CPU raycast (although slow) works fine.

while on Mac it CPU and GPU are rendering the same..

**Comment by gkjohnson** [comment]
> Yeah your setup for this was pretty interesting.
> I still need to go through the flow a bit with the generator, material, and rendering.
> Most of what I’ve seen is Texture3D slices.

Yeah effectively individual layers of the 3d texture are rendered into. You can see that the [setRenderTarget API](https://threejs.org/docs/?q=renderer#api/en/renderers/WebGLRenderer.setRenderTarget) affords this with the second argument. From the screenshot on the windows machine it doesn't look like this is working. One way to test this is to try rendering into a regular 2d WebGLRenderTarget and rendering that to see if it's actually breaking anywhere else.

> Left is Safari, right is Chrome

This seems more like a browser / shader optimization or compilation issue. The image in chrome is what I'd expect to be displayed if [this line](https://github.com/gkjohnson/three-mesh-bvh/blob/e7231174b14d854bbac9b0afb69f0ee287e54913/example/utils/RayMarchSDFMaterial.js#L127) were changed to `if ( true )`. So for some reason the shader seems to be evaluating that branch even when `intersectsSurface` is false. You can try moving some of the logic around but generally if that fixes it then it should really be reported to chrome.

> This is something I can help with! 

That would be great - let me know if you have any questions on anything!

**Comment by gkjohnson** [comment]
Looks like the android issue was related to the initial scale of the 3d texture (`100^3`). Lowering it to `75^3` fixes the issue. Feel free to make a new issue to track the other platform quirks if you'd like!
