### ISSUE TITLE
BVH construction : Improve memory consumption

### ISSUE THREAD

**Issue by SpaceIm** [gkjohnson/three-mesh-bvh#42]
I think you could improve BVH construction time and memory consumption with two tricks :

- For inner nodes, instead of creating each time `left` and `right` primitives id collections before calling the recursive function for their two children (huge memory consumption), you can mutate `origTris` when the split occurs, and only provide to the two recursive functions the range to work with (basically just a start and end index).
The final `origTris` -which is now properly ordered by primitive id of "successive leaves"- can then be a private property of the BVH object, and each leaf only stores start index and the number of primitives (+ things like min/max of the bound of course, and eventually split axis), so that it can retrieve its primitives.
This approach is valid because, in a BVH, each primitive is associated to only one leaf, even if the primitive overlaps a neighbour leaf.

- After recursive construction, tranforming the BVH nodes to a compact representation (linearization in an Array, Float32Array or Float64Array?) can save a lot of memory (and improve raycast performance, in C++ it's significant, I'm not sure in javascript).

If you are looking for implementation details, the book "Physically Based Rendering" is a great ressource. Their BVH implementation relies on two algorithms of C++ standard library (partition and nth_element, used to reorder primitives collection in two groups, depending of split method), which can be easily implemented in javascript.
They also store each node information in 32 Bytes (memory alignment), but I can't see how to achieve this kind of optimization in javascript.

**Comment by gkjohnson** [comment]
@mquander and I have discussed sorting the index (or position) array directly on the geometry object itself rather creating a new array of triangle indices to save even more memory. And representing the BVH as an array would be great and enable building the tree in a web worker, as well.

If you're interested in using this and contributing either of these features I'm happy to take a look at PRs! Thanks!

**Comment by SpaceIm** [comment]
Few months ago, I had to implement in typescript a BVH to cast rays against high resolution celestial bodies (3M primitives), built in a web worker, with nodes "pointer less" representation (Float64Array), non recursive raycast traversal etc.
So for now I don't plan to use this library, but I'll try to submit a PR when I have time ;)

**Comment by mquander** [comment]
#44 implements the first half of this suggestion.
