### ISSUE TITLE
[Question] Clipping edges - Using fat lines instead of THREE.LineSegment

### ISSUE THREAD

**Issue by PlopTheReal** [gkjohnson/three-mesh-bvh#432]
Thanks a million for this wonderful library!
I've successfully implemented a clipping with edges logic based on your example.
I'm currently trying to use Fat Lines (https://threejs.org/examples/?q=fat#webgl_lines_fat) instead of LineSegment to be able to control the line thickness without any success so far and I was wondering if you had an idea if that would be possible.
I've been also asking on three discourse (https://discourse.threejs.org/t/are-flat-lines-usable-with-the-following-exemple/38712)

Many thanks!

**Comment by gkjohnson** [comment]
Hi @PlopTheReal! Unfortunately I don't have the bandwidth to provide help here but it should definitely be possible. I would study the three.js fat lines example since it shows how to create the same shape for both gl.lines and fat line objects.

**Comment by PlopTheReal** [comment]
Thanks for your feedback!

**Comment by hoonsbory** [comment]
Hi! Thanks for creating such an awesome library.
I too am using LineSegmentsGeometry , line2 for clipping edges to thicken the line, but it seems that the section is not drawn at a certain constant. If the range is from -10 to 10, very few constants are actually drawn.
I wonder if you can help me?
