### ISSUE TITLE
How to get ordered edges of a section?

### ISSUE THREAD

**Issue by MaShizhen** [gkjohnson/three-mesh-bvh#433]
hi, By referring to the clippededges demo, I obtained all the intersection points on the section and successfully drew the section ~

However, I also need to perform some operations on the interface, such as offset, which requires the edges to be orderly.

I now reorder the edges by handling all the points. Although it can solve the problem, it is certainly not the best way to handle it.

I would like to ask if I can get the ordered edges of the section directly through shapecast?

![image](https://user-images.githubusercontent.com/31983261/171553208-4b47409f-6a4b-4b8f-9a08-65b9cfb3db31.png)

![image](https://user-images.githubusercontent.com/31983261/171553240-a273f335-6196-4947-afaf-06a3ac2e8f3e.png)

**Comment by gkjohnson** [comment]
You'll have to explain what you mean by "orderly". There otherwise is no inherent  order to the triangles that would enable a coherent order to the final edges so postprocessing them is your best bet.
