### ISSUE TITLE
Add depth parameter to raycast function for faster raycasting when precision is not needed.

### ISSUE THREAD

**Issue by theripper93** [gkjohnson/three-mesh-bvh#446]
**Is your feature request related to a problem? Please describe.**

When using raycasting on a per frame basis, sometimes it would be helpful to have a raycast method that is less precise but faster when a lot of iterations are reqired.

**Describe the solution you'd like**

Add a parameter to the raycaster for precision. Possibly specify the maximum size of the bounding box after wich the required depth is reached

In my project i use mesh-bvh to calculate a vision polygon, this requires around 100 raycasts per frame to have an accurate result, the problem is that with high poly geometries the raycast simply takes too long. If i'm raycasting inside a house for example, i don't need the individual cups to be raycast since i can easly ignore smaller objects.

**Comment by gkjohnson** [comment]
Are you already using the "firstHitOnly" field? Have you done any testing to see if this kind of optimization is actually beneficial for your use case? It should be possible using the [shapecast function](https://github.com/gkjohnson/three-mesh-bvh#shapecast) to implement your own version of this behavior. It might not be as optimal as an adjustment to the raycast function but it could be good enough.

**Comment by theripper93** [comment]
I am using the raicastFirst and there seem to be no difference from the regular ray cast. I’m not sure how to implement something using shapecast but I will try when I get the time.

**Comment by gkjohnson** [comment]
> I am using the raicastFirst and there seem to be no difference from the regular ray cast

The raycast first function should be significantly faster than the regular raycast function.

> I’m not sure how to implement something using shapecast but I will try when I get the time.

I think this is the first place to start with a feature like this. Shapecast is a generalized shape query mechanism and is good for trying new things out or implementing custom beahvior.

**Comment by gkjohnson** [comment]
I'll close this for now - I think it's best done with the shapecast functionality.
