### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by gkjohnson** [gkjohnson/three-mesh-bvh#45]
- [x] Move all source files into `src` directory
- [x] Decide on approach for initializing the extension to the THREE.Mesh.prototype & THREE.Geometry.prototype (call function? automatically include?)
- [x] Add name, version, etc to package.json
- [x] Update docs
- [x] Produce a UMD variant
- [x] Use three js named imports
- [x] #47 
- [x] #37 
- [x] #51 
- [x] Rename rollup `MeshBVH` global variable to `MeshBVHLib` (#64)

**Comment by gkjohnson** [comment]
@mquander Thoughts on how an NPM package should be structured?

What are your opinions on automatically binding to the THREE.js prototypes vs requiring explicit registration by the user? I figure that `MeshBVH` and `MeshBVHVisualizer` should be exported from the main package, as well.

**Comment by gkjohnson** [comment]
I agree -- I'll think about how to update the API when I get a chance

**Comment by gkjohnson** [comment]
@mquander Okay what do you think -- are we ready for a first publish to NPM?

**Comment by mquander** [comment]
My only complaint is that I don't really like `computeBoundsTree` and `disposeBoundsTree` as an API -- I would remove them. I can understand if you don't want to, though.

Other than that, I see no reason not to publish.

**Comment by gkjohnson** [comment]
Okay I think I'll publish as-is for now and we can re-evaluate the API in a future release.
