### ISSUE TITLE
How to run three-mesh-bvh/example ?

### ISSUE THREAD

**Issue by SCHI2022** [gkjohnson/three-mesh-bvh#453]
**Describe the bug**

A clear and concise description of what the bug is. Before submitting, please remove unnecessary sections.

**To Reproduce**

3. See error

***Code***

```js
// code goes here
```

***Live example***

-

**Expected behavior**

**Screenshots**

If applicable, add screenshots to help explain your problem (drag and drop the image).

**Platform:**

 - Device: [Desktop, ![Capture](https://user-images.githubusercontent.com/109940602/185546485-46fcefc6-6ca7-442c-8e76-434d1ddad939.PNG), ...]
 - OS: [Windows, MacOS, Linux, Android, iOS, ...]
 - Browser: [Chrome, Firefox, Safari, Edge, ...]
 - Three.js version: [r???]
 - Library version: [v???]

**Comment by gkjohnson** [comment]
- Run `npm start`
- Then visit `localhost:9080/example/dev-bundle/<demo-name>.html`
