### ISSUE TITLE
why  bvh need rebuild geometry index...

### ISSUE THREAD

**Issue by liuyehua** [gkjohnson/three-mesh-bvh#454]
I merge many geometry in one geometry，before merge i through store the geometry index range to help me when i do raycaster can find which geometry i catched，but use bvh the index order are messed up，I can't find the model before merging through the original stored index range，bvh Is it possible not to shuffle the index order?

**Comment by gkjohnson** [comment]
The geometry index is reorganized to so the BVH can be stored in a memory-optimal way. Currently there is no way to disable modification of the index buffer. If you want to keep track of which items are which you can create a custom vertex attribute that stores an object id so it can be used to look up the selected object.
