### ISSUE TITLE
OrientedBox type does not extend Box3

### ISSUE THREAD

**Issue by krispya** [gkjohnson/three-mesh-bvh#468]
Hello! While using `OrientedBox` the type would report as not having `min` or `max` on the object which looked odd. When I peeked at the type definition I saw that the `OrientedBox` type was not extending `Box3`.

**Comment by gkjohnson** [comment]
There are no ts definition files in the project so unfortunately I can't help with typing issues. It's probably best to discuss on a typescript or code editor issue than here.

**Comment by krispya** [comment]
Oh I had no idea. Is there any interest in providing types?

**Comment by gkjohnson** [comment]
Oh sorry - there actually are type definitions 😅 I forgot they'd been added. It looks like OrientedBox is not extending from Box3 in the types. Would you like to make a PR to fix the issue?

https://github.com/gkjohnson/three-mesh-bvh/blob/master/src/index.d.ts#L315

**Comment by krispya** [comment]
> Oh sorry - there actually are type definitions 😅 I forgot they'd been added. It looks like OrientedBox is not extending from Box3 in the types. Would you like to make a PR to fix the issue?
> 
> https://github.com/gkjohnson/three-mesh-bvh/blob/master/src/index.d.ts#L315

😅 Good to know I'm not crazy! Yeah I'll make a PR when I get some time. I've been using the library a lot so I'm happy to give back.

**Comment by Cevered** [comment]
I assumed I was the only one, but I didn't realize this was a problem.

**Comment by gkjohnson** [comment]
Please feel free to submit a PR to fix the issue!
