### ISSUE TITLE
HELP: Physics

### ISSUE THREAD

**Issue by Cevered** [gkjohnson/three-mesh-bvh#469]
![image](https://user-images.githubusercontent.com/66314321/194951796-d30c33c8-5e80-4eba-a4fb-366b70e210fb.png)

![image](https://user-images.githubusercontent.com/66314321/194951912-b16747b1-f3c9-46fc-a030-18e123c625bf.png)

I believe these two are for spheres and capsules.

nevertheless, how would I be able to use Box3 in the same way?

**Comment by gkjohnson** [comment]
Hello! The physics demo is just to show basic feasibility of using the BVH as a physics world. If you'd like to add something like boxes you'll have to investigate that yourself - unfortunately I don't have the bandwidth to dive into more robust physics simulations and collision detection with all objects. A proper physics engine for simulating boxes would require things like angular velocity, forces, etc to get them to rotate and fall as expected.

**Comment by Cevered** [comment]
Oh no no no no no 😂

That's not what I meant; all I wanted was something simple, similar to the demo, but with a box in place of the spheres and capsules to obtain the normal and the depth of the intersection.

However, I simply made a sphere out of the box before using it, which is wrong, in my opinion.

**Comment by gkjohnson** [comment]
Unfortunately the answer is still more complicated than the sphere or capsule case (which is basically the same as a sphere). You'll have to write something that detects where on the box it intersects a triangle and adjusts it along the vector to the collision point such that it no longer intersects triangle.

I haven't had to deal with this before so I have no solution immediately available. I recommend asking on a more general forum like the three.js discord or discourse forums.

**Comment by Cevered** [comment]
Understood, thank you for your response.
