### ISSUE TITLE
Assign default maximum depth < ∞

### ISSUE THREAD

**Issue by mquander** [gkjohnson/three-mesh-bvh#47]
I'm not sure what a good maximum depth is, but it seems to me a maximum depth of infinity means that fishy models can kind of DoS non-SaH trees by e.g. making sure that exactly one triangle gets partitioned off every time, causing construction to take forever, overflow the stack, run out of memory, make raycasting very slow, or all of the above. I think some conservative default of, say, 20-30 would be wiser. Assuming reasonable splits are being created that should suffice for models up to millions of tris.

**Comment by gkjohnson** [comment]
The bounds trees generated in our tests and benchmarks are at depths of 19 and 22 respectively for a bit more context. I'm wondering if setting this to a safer / lower value should be the responsibility of the application generating the BVH rather than built in as the default?

**Comment by mquander** [comment]
I would definitely make the default some maximum -- what it should be, I'm not sure.

If you're concerned about people accidentally hitting the maximum without realizing it's a relevant tunable, it might be worth making a console warning come out if the maximum is reached.

**Comment by gkjohnson** [comment]
With the merged pickle_rick model I'm seeing that the extremes are 
```js
{
  "depth":{"min":9,"max":32},
  "tris":{"min":1,"max":4570}
}
```

I'm thinking maybe 35 or 40 or so being the default? I think adding the warning log is a good idea
