### ISSUE TITLE
StaticGeometryGenerator() gives me RangeError: Invalid type array

### ISSUE THREAD

**Issue by c4b4d4** [gkjohnson/three-mesh-bvh#479]
So, I'm trying to generate a single mesh from meshes that have multiple children, and some of them sometimes may have skinned meshes as well.

I see there's a method called `StaticGeometryGenerator()`, but whenever I try to use it it throws `RangeError`s like the following:

<img width="544" alt="Screen Shot 2022-10-18 at 1 38 36" src="https://user-images.githubusercontent.com/375183/196308740-18e95a24-0107-4839-a0cd-d89aa67b765d.png">

<img width="531" alt="Screen Shot 2022-10-18 at 0 47 26" src="https://user-images.githubusercontent.com/375183/196303925-6a840f25-90f8-491d-bc72-7d2b9930d5d1.png">

And here is what the actual values of those variables are:

<img width="531" alt="Screen Shot 2022-10-18 at 1 36 52" src="https://user-images.githubusercontent.com/375183/196308605-f4b936d7-2151-4f7a-9940-4efa4885cccb.png">

Which corresponds to this part of the code:

https://github.com/gkjohnson/three-mesh-bvh/blob/d2dafbb61e345dc969b40f35c23a2d0f9815ac24/src/utils/StaticGeometryGenerator.js#L72

This is how I'm trying it (**root_model** is a loaded GLB):

```
const wireframeMaterial = new THREE.MeshBasicMaterial( {
    wireframe: true,
    transparent: true,
    opacity: 0.5,
    depthWrite: false,
} );
const meshHelper = new THREE.Mesh( new THREE.BufferGeometry(), wireframeMaterial );
const generator = new StaticGeometryGenerator( root_model );
generator.attributes = [ 'position' ];
generator.generate(meshHelper.geometry);
```

Why could I be getting this error? I've tried with multiple meshes and still the same. And tried as well by just telling to use the `position` attribute.

I'm using **0.141.0** three version.

**Comment by gkjohnson** [comment]
Can you provide a js fiddle showing the issue?

**Comment by gkjohnson** [comment]
A for-in loop is a valid way to iterate over an array. Modifying built in prototypes is never a great idea unless you're using a polyfill for reasons like this generally so I don't support making any changes to the project. If you insist on modifying it you should make the property non-enumerable.
