### ISSUE TITLE
selection or BHV selection with Orthographic camera

### ISSUE THREAD

**Issue by nnvvijay** [gkjohnson/three-mesh-bvh#480]
Hi,
This is regarding selection.html example. In our application, we are trying to use the BHV and do the selection similar to "selection.html" shown. It's working fine when we have a perspective camera but not working(no selections) when we have an orthographic camera.

Is this selection logic supposed to work with an Orthographic camera?

Is there anything I need to change?

--Vijay

**Comment by nnvvijay** [comment]
Can you tell me what I need to change to support orthographic or any direction?

**Comment by gkjohnson** [comment]
It's been awhile since I've touched that example too much. I'd look at anything relating to the camera projection matrix and transform to make sure it's sensible for orthographic cameras.

**Comment by nnvvijay** [comment]
Thank you for your support
