### ISSUE TITLE
unable to successfully load bhv

### ISSUE THREAD

**Issue by PatONeil** [gkjohnson/three-mesh-bvh#482]
I have used the following imports
				"imports": {
					"three": "../build/three.module.js",
					"three/addons/": "./jsm/"
					"three-mesh-bvh": "https://unpkg.com/three-mesh-bvh@^0.5.10/build/index.module.js"
				}
I get the following error in chrome browser.

Uncaught SyntaxError: Failed to parse import map: invalid JSON
test.html:1 Uncaught TypeError: Failed to resolve module specifier "three". Relative references must start with either "/", "./", or "../".
es-module-shims.js:741 Uncaught SyntaxError: Expected ',' or '}' after property value in JSON at position 101
    at JSON.parse (<anonymous>)
    at es-module-shims.js:741:113
(anonymous) @ es-module-shims.js:741
setTimeout (async)
(anonymous) @ es-module-shims.js:743
Promise.catch (async)
processImportMap @ es-module-shims.js:743
processImportMaps @ es-module-shims.js:674
(anonymous) @ es-module-shims.js:715

Is there a simple way for me to add necessary bhd code to the threejs distribution that I have downloaded?

Not an issue but a questions
1)  Do I need to add "geometry.computeBoundsTree();" to every mesh/geometry I create or is it done automatically?
2)  How do I exclude some geometry from being clicked upon?

Regards Pat

**Comment by gkjohnson** [comment]
It doesn't look like these are three-mesh-bvh specific issues. Unfortunately I don't have the bandwidth to answer general javascript or three.js questions thoroughly. I recommend asking at the [three.js forums](https://discourse.threejs.org/) for help on these topics.

**Comment by PatONeil** [comment]
My mistake, sorry.....
