### ISSUE TITLE
Drawing an outline (silhouette) around the object

### ISSUE THREAD

**Issue by vladmdgolam** [gkjohnson/three-mesh-bvh#493]
Hi everyone!

I am trying to find a way to draw a silhouette of an object in three.js with a line geometry (so outline shaders won't help), and three-mesh-bvh seems to be a great way of doing it. I want then to use this line to draw a text following this path (shown as purple on the picture).

There's a [edge projection example](https://gkjohnson.github.io/three-mesh-bvh/example/bundle/edgeProjection.html), and it already solves the problem, but has a lot of inner faces that I'm trying to get rid of. On the basic level, I think that we have to filter out all the edges that have any other edges that are closer to BVH. And now I'm trying to find a way to do this. 

Would appreciate any help! Thanks in advance

P.S.: object on the picture is 3d, but rendered without any shading so it looks flat

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/10697289/204107873-ea7f2e74-439b-4a4b-83b7-a10e4ae986a5.png">

**Comment by gkjohnson** [comment]
Hello! Surely there's a reasonably fast solution for this but I don't have any immediate approach of the top of my head and don't have the bandwidth to investigate further. I recommend asking over on the three.js discourse forums to reach a broader community for help:

https://discourse.threejs.org/

**Comment by vladmdgolam** [comment]
@gkjohnson thanks for the quick response! will try my luck on the forum
