### ISSUE TITLE
Why does raycaster take longer when the mesh is not very complex?

### ISSUE THREAD

**Issue by whucj** [gkjohnson/three-mesh-bvh#498]
Load a gltf file based on threejs, where the mesh is not too complicated. I compared the time consumption between the original rayCaster method and the establishment of BVH, and found that the time will increase instead.

**Comment by gkjohnson** [comment]
The issue template is there for a reason - please provide a working example of your issue other I can only guess.

**Comment by makc** [comment]
well if you use 2 triangles plane it is obvious that they will both end up in the same bounding box, so traversing the tree will only waste some extra time.

**Comment by whucj** [comment]
> The issue template is there for a reason - please provide a working example of your issue otherwise I can only guess.

After constructing bvh, is there a critical value for how many triangle meshes are more efficient?

**Comment by whucj** [comment]
> well if you use 2 triangles plane it is obvious that they will both end up in the same bounding box, so traversing the tree will only waste some extra time.

Yes, the mesh triangles I have encountered are relatively small, and each mesh may have up to 100 triangles.

**Comment by gkjohnson** [comment]
> After constructing bvh, is there a critical value for how many triangle meshes are more efficient?

Your question is not clear. Again please provide a working example of the problem or discrepency using JSFiddle or other JS environment.

**Comment by DennisSmolek** [comment]
> > each mesh may have up to 100 triangles.

The basic Raycast Demo uses 500 rays against a Polymesh with 80,000 Triangles.

You are trying to hammer a nail by smashing it with a X-Ray machine…

BVH is used to make big distances easier to cross, some utilities to improve accuracy etc, it won’t be more efficient for things in a small area or a basic shape
