### ISSUE TITLE
package.json leads to wrong export

### ISSUE THREAD

**Issue by drcmda** [gkjohnson/three-mesh-bvh#509]
we're getting reports like this one:

<img width="368" alt="Screenshot 2023-01-03 at 00 39 03" src="https://user-images.githubusercontent.com/2223602/210285151-4cd22826-77a5-410a-834b-4853fd40da12.png">

the cause is

```json
{
  "name": "three-mesh-bvh",
  "version": "0.5.20",
  "description": "A BVH implementation to speed up raycasting against three.js meshes.",
  "module": "src/index.js",
  "main": "build/index.umd.cjs",
```

index.js is untranspiled and contains some js features that aren't prevalent enough yet, so a lot of tools will not be able to handle it.

"module" should most likely point towards "build/index.module.cjs"

**Comment by CodyJasonBennett** [comment]
Node resolution is working correctly here, and `module` expects ESM not CJS. This would merely be catching on the use of optional chaining which is unsupported in Webpack 4 and older (<14) Node runtimes.

**Comment by gkjohnson** [comment]
I'll release a new version with no optional chaining.

**Comment by gkjohnson** [comment]
Just made a new release.

**Comment by drcmda** [comment]
> Node resolution is working correctly here, and `module` expects ESM not CJS. This would merely be catching on the use of optional chaining which is unsupported in Webpack 4 and older (<14) Node runtimes.

that was a type, i meant "module": "build/index.modules.js" there is an esm file in the build folder that is not actually used since package.json picks up /src/index. @gkjohnson i don't optional chaining was the problem, it's just linking the wrong file.

**Comment by gkjohnson** [comment]
> rollup will take care of such things via babel-env, it knows that optional chaining is not yet <1% browser use, it has already swatted it in build/index.module.js

Babel isn't part of the rollup bundle process here so the optional chaining was still present in `index.module.js`.

> if you link it up correctly you never need to worry about writing code in a specific way, the output will always be in accordance with browsers-list/caniuse.

I've used babel plenty in the past - I'd just prefer to remove the one instance of problematic syntax. There's otherwise nothing exotic about code written in this project that really justifies it.
