### ISSUE TITLE
Add method to serialize to JSON

### ISSUE THREAD

**Issue by neilrackett** [gkjohnson/three-mesh-bvh#510]
Calculating BVH for a large model can take a very long time.

While it's currently possible to `serialize` BVH data into a format that can easily be transferred between workers and the main thread, it cannot easily be serialized into a format that can be exported as JSON, imported and `deserialize`d later.

It would be great if you could do this:

```javascript
const geometry = new THREE.TorusKnotGeometry( 10, 3, 100, 16 )
const bvh = new MeshBVH( geometry );
const json = MeshBVH.serializeJson( bvh );

// ... send to database (or add to GLTF extras?) for use later

const response = await fetch('bvh.json');
const json = await response.json();
const deserializedBVH = MeshBVH.deserializeJson( json, geometry );
geometry.boundsTree = deserializedBVH;
```

Possibly also useful as part of CLI tool suggestion (#367)?

**Comment by gkjohnson** [comment]
There are complexities in generating a BVH and storing in glTF which are outlined in #367, unfortunately. The serialized format is fairly simple, though, so implementing this at the app level should be straight forward - whether it be a file, database entry, browser cache storage, etc.

But either way I don't think JSON is an optimal format for storing the binary data required by the serialized format (file size, parse time). It would be best to save separate files or create a binary format to save the file to disk.

**Comment by neilrackett** [comment]
Thanks for the quick response - I'll investigate what we might be able to implement at app level as an alternative and let you know if we come up with anything useful!

**Comment by gkjohnson** [comment]
Sounds good -- I'll close this for now!

**Comment by neilrackett** [comment]
So, if you're looking to cache BVH and have just stumbled across this thread:

1. While perhaps not optimal, JSON works surprisingly well, gzips nicely, requires no additional libraries and is easy to store, so here are some [BVH-to-JSON tools](https://github.com/mesmotronic/three-mesh-bvh-json) you might find useful
2. If you only need local browser caching, [localForage](https://www.npmjs.com/package/localforage) can store a serialized BVH as-is, e.g. `localForage.setItem("my-bvh", MeshBVH.serialize(bvh))` to save and `geometry.boundsTree = MeshBVH.deserialize(await localForage.getItem("my-bvh"), geometry)` to load
