### ISSUE TITLE
Calculation Method of PlayerIsOnGround in characterMovement.html Demo

### ISSUE THREAD

**Issue by Steve245270533** [gkjohnson/three-mesh-bvh#518]
**Describe the bug**

In the characterMovement.html demo, the method for calculating playerIsOnGround may experience jitter. When a character walks against a wall, the calculation result of playerIsOnGround is sometimes true and sometimes false, which makes it difficult to determine the value of playerIsOnGround to set the character's jumping action
[demo-link](https://github.com/gkjohnson/three-mesh-bvh/blob/da5a92012cef3bc91771cc76d60c3e75167e9b6b/example/characterMovement.js#L395)

***Code***

```js
// if the player was primarily adjusted vertically we assume it's on something we should consider ground
playerIsOnGround = deltaVector.y > Math.abs( delta * playerVelocity.y * 0.25 );
```

**Expected behavior**

Can correctly calculate the result of playerIsOnGround

**Screenshots**

![image](https://user-images.githubusercontent.com/46118247/226161007-a2fef5a2-87f2-4e45-907b-34a2460b67f1.png)

**Platform:**

 - Device: Desktop
 - OS: Windows
 - Browser: Chrome
 - Three.js version: [r148]
 - Library version: [v0.5.23]

**Comment by gkjohnson** [comment]
Generally these demos are intended to be a starting point so you should look into adjusting the behavior you want for yourself - but I've taken a quick look and adjusted the behavior in a1665f35bc3b17f6832deb4aa9a7e422695dceec. See if that works for you.
