### ISSUE TITLE
SharedArrayBuffer can not be in transfer list

### ISSUE THREAD

**Issue by Innovgame** [gkjohnson/three-mesh-bvh#523]
GenerateMeshBVHWorker

```js
const worker= new GenerateMeshBVHWorker();
worker.generate(geometry, { useSharedArrayBuffer: true }).then((bvh: MeshBVH) => {
     geometry.boundsTree = bvh;
});
```

DataCloneError: SharedArrayBuffer can not be in transfer list

**Comment by gkjohnson** [comment]
Hello! Thanks for the catch. Would you like to make a PR that guards against this case? It's hopefully as simple as just making a condition that doesn't add the bounds tree arrays to the transfer list if they are shared array buffers.
