### ISSUE TITLE
raycaster.firstHitOnly and raycaster.intersectObjects difficult

### ISSUE THREAD

**Issue by Runasia** [gkjohnson/three-mesh-bvh#527]
Hi,
I wirte this 
`     const raycaster = new Raycaster()
      raycaster.firstHitOnly = true;`

attribute firstHitOnly of Raycaster()  not exist in  three.module.js.(i try ctrl+f  
the version is 
 ` "name": "three",
  "version": "0.149.0",`

another difficult is raycaster.intersectObjects return a undefine value.
this is my code 
`raycaster.setFromCamera(mouse, camera);
 raycaster.intersectObjects(ifcModels,true);`
I debug in  Google Chrome and make sure mouse & camera & ifcmodels has value
![image](https://github.com/gkjohnson/three-mesh-bvh/assets/39799280/338d0a61-8c7a-48d9-bb87-3743ea95021b)

and thanks seeing this issue.

**Comment by gkjohnson** [comment]
> attribute firstHitOnly of Raycaster() not exist in three.module.js.(i try ctrl+f

This is specified as a part of the three-mesh-bvh and the dts files.

Can you check if the raycasting works correctly without three-mesh-bvh? There should be no difference in the raycasting results between three.js and three-mesh-bvh.

**Comment by Runasia** [comment]
> This is specified as a part of the three-mesh-bvh and the dts files.
Thanks！Because of your suggestion i finded that .  due to 
`import {Raycaster, Vector2} from "three";` 
So i make a mistake to find Raycaster's attribute (firstHitOnly)  in three.js .
and my idea even can't find  not defined firstHitOnly and think Raycaster just belone in three.module.js . 
I don't know why my idea "ctrl + Click on the left of mouse"  it's will go to 
> Can you check if the raycasting works correctly without three-mesh-bvh? There should be no difference in the raycasting results between three.js and three-mesh-bvh.
wait a minute .

**Comment by Runasia** [comment]
> This is specified as a part of the three-mesh-bvh and the dts files.
Thanks！Because of your suggestion i finded that .  due to 
`import {Raycaster, Vector2} from "three";` 
So i make a mistake to find Raycaster's attribute (firstHitOnly)  in three.js .
and my idea even can't find  not defined firstHitOnly and think Raycaster just belone in three.module.js . 
I don't know why my idea "ctrl + Click on the left of mouse"  it's will go to 
> Can you check if the raycasting works correctly without three-mesh-bvh? There should be no difference in the raycasting results between three.js and three-mesh-bvh.
wait a minute .

**Comment by gkjohnson** [comment]
You should submit a bug to IFC.js with a minimal example of the problem, then. There should be no difference in results between three.js' raycast results and three-mesh-bvhs.
