### ISSUE TITLE
Provide example for use with InstancedMesh

### ISSUE THREAD

**Issue by Triazic** [gkjohnson/three-mesh-bvh#531]
**Is your feature request related to a problem? Please describe.**

I can't get three-mesh-bvh working in my project with InstancedMeshes. 

**Describe the solution you'd like**

Please add documentation / supply an example for how to successfully use three-mesh-bvh with three's [InstancedMesh](https://threejs.org/docs/#api/en/objects/InstancedMesh)

**Additional context**

I get cryptic errors ala ```Triangle.getInterpolation is not a function```. I don't need you to figure out my code, I just need an example of expected syntax usage with InstancedMeshes.

**Comment by gkjohnson** [comment]
> Triangle.getInterpolation is not a function.

You are using an old version of three.js. The latest version of the project is intended for use with release 151 and later.

**Comment by Triazic** [comment]
Thanks, I'll give it a go tomorrow and post back here

**Comment by melicheradam** [comment]
Hello @Triazic , 

any luck of getting this work? What i want to achieve is to use this library with InstancedMesh and get the clicked (intersected) object index in the mesh

Most examples provided work just with copying positions etc, but how can I know which object was selected?
