### ISSUE TITLE
Question: how to implement Blender proportional edit feature but via three-mesh-bvh

### ISSUE THREAD

**Issue by tomhsiao1260** [gkjohnson/three-mesh-bvh#532]
Hi, Garrett Johnson

Sorry for bothering in this way and thanks for this open source project. It helps me a lot. Currently, I want to implement a [proportional edit feature](https://docs.blender.org/manual/en/2.79/editors/3dview/object/editing/transform/control/proportional_edit.html#influence) on a three.js project. I think perhaps I can use three-mesh-bvh to achieve that but after struggling a while, I still don't know how to do it correctly. Any advice or hints for such a demand? Thanks in advance!

![editors_3dview_object_editing_transform_control_proportional-edit_influence](https://github.com/gkjohnson/three-mesh-bvh/assets/31985811/c79df422-2aeb-446f-8c3e-088dda4bd317)

**Comment by gkjohnson** [comment]
Hello! The first step is to understand how to implement this without a BVH - then the performance can be improved with a refitting BVH. Unfortunately I don't have the bandwidth to provide help with this but I can recommend asking at the three.js forums to get a start:

https://discourse.threejs.org/
