### ISSUE TITLE
Add Basic Information about Bounding Volume Hierarchy

### ISSUE THREAD

**Issue by BekBoris** [gkjohnson/three-mesh-bvh#533]
For a person who just came to the 3d world, I think small information about what is BVH(Bounding Volume Hierarchy) would be nice, I read this article it is very clear the basic idea is understandable. I am suggesting adding the small text about BVH and attaching this link to it.
https://en.wikipedia.org/wiki/Bounding_volume_hierarchy

**Comment by gkjohnson** [comment]
Yes I think this is a good idea. Would you like to make a PR into the README with what you were thinking?
