### ISSUE TITLE
ExtendedTriangle.intersectsTriangle is Error

### ISSUE THREAD

**Issue by etimes2008** [gkjohnson/three-mesh-bvh#538]
***Code***

```js
let line = new THREE.Line3();
if ( new ExtendedTriangle( new THREE.Vector3( -5.781455993652344, -7.291503906249993, -30 ), new THREE.Vector3( -5.781455993652344, -7.291503906250007, 30 ), new THREE.Vector3(0, -7.291503906249993, -30) ).intersectsTriangle( new ExtendedTriangle( new THREE.Vector3( -5.781455993652344, -7.29150390625, -4.098872661590576 ), new THREE.Vector3( -6.386039733886719, -11.163619995117188, -4.485982418060303 ), new THREE.Vector3(13.468360900878906, -6.142303466796875, -4.028029918670654) ), line ) ) {
	
	console.log(line);

}
```
selection2.js:619 Line3 {start: Vector3, end: Vector3}end: Vector3 {x: -5.781455993652342, y: 7.532732270002408, z: -4.960256306735925}start: Vector3 {x: -2.495039045841784, y: -7.291503906249999, z: -4.106463334691071}[[Prototype]]: Object

end: Vector3 {x: -5.781455993652342, y: 7.532732270002408, z: -4.960256306735925} y is error

**Comment by gkjohnson** [comment]
Please provide an explanation of the problem I will have to close this issue.

**Comment by etimes2008** [comment]
let line = new THREE.Line3();
if ( new ExtendedTriangle( 
		new THREE.Vector3( -5.781455993652344, -7.291503906249993, -30 ), 
		new THREE.Vector3( -5.781455993652344, -7.291503906250007, 30 ), 
		new THREE.Vector3(0, -7.291503906249993, -30) 
			).intersectsTriangle( 
				new ExtendedTriangle( 
						new THREE.Vector3( -5.781455993652344, -7.29150390625, -4.098872661590576 ), 
						new THREE.Vector3( -6.386039733886719, -11.163619995117188, -4.485982418060303 ), 
						new THREE.Vector3(13.468360900878906, -6.142303466796875, -4.028029918670654)
					), line ) ) {
						console.log(line);
					}
console.log(line);

===>
result:
start: Vector3 {x: -2.495039045841784, y: -7.291503906249999, z: -4.106463334691071}
end: Vector3 {x: -5.781455993652342, y: 7.532732270002408, z: -4.960256306735925}

My English is not very good, it is the numerical value of the vertex of the triangle surface above, the coordinates of the line obtained are wrong,
One of the results is wrong

line.end.y value is wrong.
line.end.y != 7.532732270002408
line.end.y == -7.532732270002408 is right

**Comment by etimes2008** [comment]
![微信截图_20230718143714](https://github.com/gkjohnson/three-mesh-bvh/assets/2875384/fb31ca83-14e0-4883-a5f1-f3e0accc4318)

**Comment by etimes2008** [comment]
![微信截图_20230718145006](https://github.com/gkjohnson/three-mesh-bvh/assets/2875384/f539b45b-d6f1-404d-b88c-1978aded9460)

**Comment by gkjohnson** [comment]
Looks like it's not detecting the intersection at all. If the triangle order is flipped then it works so there's a bug in the function:

<img width="660" alt="image" src="https://github.com/gkjohnson/three-mesh-bvh/assets/734200/76657c80-5838-40dc-8b9a-ff7d915a27cb">

The reference code for specifying the triangles in `intersectTriangle.js`:

```js
t1.a.set( -5.781455993652344, -7.291503906249993, -30 );
t1.b.set( -5.781455993652344, -7.291503906250007, 30 );
t1.c.set(0, -7.291503906249993, -30);

t2.a.set( -5.781455993652344, -7.29150390625, -4.098872661590576 );
t2.b.set( -6.386039733886719, -11.163619995117188, -4.485982418060303 );
t2.c.set(13.468360900878906, -6.142303466796875, -4.028029918670654);
```

**Comment by etimes2008** [comment]
thank you

**Comment by gkjohnson** [comment]
This is not fixed, yet.

**Comment by etimes2008** [comment]
0.6.2
new version,
This version is still a bug

t1.a.set( -15.430519104003906, 29.432968139648445, -25 );
t1.b.set( -15.430519104003906, 29.43296813964843, 25 );
t1.c.set( 0, 29.432968139648445, -25 );
t2.a.set( -4.854911804199219, 36.03794860839844, 0.0777292251586914 );
t2.b.set( -15.430519104003906, 29.432968139648438, -1.905876636505127 );
t2.c.set( -16.118995666503906, 26.962722778320312, -2.8487582206726074 );

Try these data
result is error

**Comment by etimes2008** [comment]
![屏幕截图 2023-07-20 095623](https://github.com/gkjohnson/three-mesh-bvh/assets/2875384/c867be63-d900-4e0c-ae41-c76e53b708a5)

**Comment by etimes2008** [comment]
> This is not fixed, yet.

0.6.2
new version,
This version is still a bug

t1.a.set( -15.430519104003906, 29.432968139648445, -25 );
t1.b.set( -15.430519104003906, 29.43296813964843, 25 );
t1.c.set( 0, 29.432968139648445, -25 );
t2.a.set( -4.854911804199219, 36.03794860839844, 0.0777292251586914 );
t2.b.set( -15.430519104003906, 29.432968139648438, -1.905876636505127 );
t2.c.set( -16.118995666503906, 26.962722778320312, -2.8487582206726074 );

Try these data
result is error

**Comment by gkjohnson** [comment]
Thank you - this code is sensitive to floating point error so it's expected. Reporting other buggy scenarios is helpful.

But please make a new issue for this and additional bugs. It makes it easier to track.

**Comment by gkjohnson** [comment]
@etimes2008 - the issue should be fixed, now. I will will publish a new version in the next couple days. Please let me know if you find more issues.
