### ISSUE TITLE
MeshBVH.prototype.intersectsBox fails when box's position is not 0,0,0

### ISSUE THREAD

**Issue by lewibs-Powern** [gkjohnson/three-mesh-bvh#539]
**Describe the bug**

I think this is a bug however it may just be misuse. The intersectsBox seems to fail when the object from which the box was created has a position that is not the center of the scene it fails to intersect. 

**To Reproduce**

1. run the provided code
2. check the console to see that the result was false

***Code***

```js
        const geometry = new BoxGeometry( 10, 10, 10 ); 
        const material = new MeshBasicMaterial( { color: 0xffff00 } ); 
        const object = new Mesh( geometry, material );
        object.position.set(11,11,11);

        const box = new Box3();
        box.setFromObject(object);

        const meshBVH = new MeshBVH(object.geometry);
        
        let boxToBvh = new Matrix4();
        let res = meshBVH.intersectsBox(box, boxToBvh);
        console.log(res); //should be true but is false
```

**Expected behavior**
I expect the console log to show true. This is because the box was made around the object and then that same object was used to make the MeshBVH. The log does show true when the position is set to anything within a 10,10,10 position.

**Platform:**

 - Device: Desktop
 - OS: Linux
 - Browser: Firefox
 - Three.js version: "^0.135.0"
 - Library version: "^0.5.17"

**Comment by gkjohnson** [comment]
You're just passing an identity matrix into the function so you cannot expect the box or mesh to have any relative transformation. From the docs:

> The boxToBvh parameter is the transform of the box in the meshes frame.

You need to compute the transform like so:

```js
let boxToBvh = new Matrix4().copy( mesh.matrixWorld ).invert();
let res = meshBVH.intersectsBox(box, boxToBvh);
```
