### ISSUE TITLE
acceleratedRaycast will result in parts of model not showing on mobile

### ISSUE THREAD

**Issue by CuratorHQ** [gkjohnson/three-mesh-bvh#548]
**Describe the bug**

Meshbvh (acceleratedRaycast) will result in certain parts of an model to not show on mobile safari. 

**To Reproduce**

1. Apply acceleratedRaycast to the glb file
2. Check file on mobile device

***Code***

Mesh.prototype.raycast = acceleratedRaycast

***Live example***

[bio_chamber_unit_-_free_asset.glb.zip](https://github.com/gkjohnson/three-mesh-bvh/files/12285438/bio_chamber_unit_-_free_asset.glb.zip)

**Expected behavior**

Glb file should display all parts.

**Screenshots**

![IMG_3576 1](https://github.com/gkjohnson/three-mesh-bvh/assets/116768835/c207797b-7265-4365-91e3-591017c87f24)
(with meshbvh)

![IMG_3577](https://github.com/gkjohnson/three-mesh-bvh/assets/116768835/b7c9da3b-4028-4bdd-b061-11a7f8b4fc1c)
(without meshbvh)

**Platform:**

 iOS mobile

Safari 
Threejs latest version
Meshbvh latest version

**Comment by gkjohnson** [comment]
Please provide a full working live example that shows the issue.

**Comment by CuratorHQ** [comment]
https://jsfiddle.net/5nsv9t8b/9/
Takes a .glb file and applies computeBoundTree to all the object's geometries.
[bio_chamber_unit_-_free_asset.glb.zip](https://github.com/gkjohnson/three-mesh-bvh/files/12295001/bio_chamber_unit_-_free_asset.glb.zip)

**Comment by CuratorHQ** [comment]
Sorry for the delay. Here's the working example. The shader is causing part of the glb to not show. 
https://plnkr.co/edit/MiZuORjbLnkasl11?open=Hello.js&deferRun=1
[bio_chamber_unit_-_free_asset.glb.zip](https://github.com/gkjohnson/three-mesh-bvh/files/12317958/bio_chamber_unit_-_free_asset.glb.zip)

**Comment by gkjohnson** [comment]
You need to provide step by step instructions on how to reproduce this issue and describe what I'm supposed see with screenshots from your demo - I can't spend my time guessing trying to figure out how to see this problem. The BVH also just rearranges the index buffer which won't affect whether something draws so I'm highly skeptical there's an issue here that isn't in your code. That considered please make a simplified demo showing the issue with no extraneous code. Your example has post processing and a lot of unused imports.
