### ISSUE TITLE
The shapecast function in grid selection, how to select multiple models in the scene?

### ISSUE THREAD

**Issue by Sea-DH1** [gkjohnson/three-mesh-bvh#549]
I want to directly select multiple models of the scene, how to set toScreenSpaceMatrix here? And how to calculate model occlusion?

toScreenSpaceMatrix
     .copy(mesh.matrixWorld)
     .premultiply(camera.matrixWorldInverse)
     .premultiply(camera.projectionMatrix)

**Comment by gkjohnson** [comment]
> I want to directly select multiple models of the scene, how to set toScreenSpaceMatrix here?

For each mesh you have to compute a new screen space matrix using the appropriate matrixWorld.

> And how to calculate model occlusion?

See #109. This is not supported and requires a different technique and is not without its limiations.

**Comment by Sea-DH1** [comment]
> > I want to directly select multiple models of the scene, how to set toScreenSpaceMatrix here?
> 
> For each mesh you have to compute a new screen space matrix using the appropriate matrixWorld.
> 
> > And how to calculate model occlusion?
> 
> See #109. This is not supported and requires a different technique and is not without its limiations.

This is to multiply the world matrices of all the models, right?

**Comment by gkjohnson** [comment]
No - multiplying all the mesh matrices together will not yield anything useful. You need to perform the same lasso step for each mesh including recomputing that matrix:

```js
// matrixWorld transforms triangles into world space for that mesh
toScreenSpaceMatrix.copy(mesh.matrixWorld)

// applying this matrix transforms into local camera space
.premultiply(camera.matrixWorldInverse)

// applying this matrix transforms into clip screen space.
.premultiply(camera.projectionMatrix)
```

I'd recommend looking into understanding this kinds of frame transformations. The demos are intended to show capabilities but extending them and using them in other ways requires a bit more understanding in some cases.

**Comment by Sea-DH1** [comment]
> No - multiplying all the mesh matrices together will not yield anything useful. You need to perform the same lasso step for each mesh including recomputing that matrix:
> 
> ```js
> // matrixWorld transforms triangles into world space for that mesh
> toScreenSpaceMatrix.copy(mesh.matrixWorld)
> 
> // applying this matrix transforms into local camera space
> .premultiply(camera.matrixWorldInverse)
> 
> // applying this matrix transforms into clip screen space.
> .premultiply(camera.projectionMatrix)
> ```
> 
> I'd recommend looking into understanding this kinds of frame transformations. The demos are intended to show capabilities but extending them and using them in other ways requires a bit more understanding in some cases.

okay, thank you

**Comment by gkjohnson** [comment]
Please close your issues when finished
