### ISSUE TITLE
Check maxNodeTris after split

### ISSUE THREAD

**Issue by gkjohnson** [gkjohnson/three-mesh-bvh#55]
The geometry in the benchmark with the default options winds up having the following min and max triangle counts:

```
tris: { min: 1, max: 76 }
```

despite the `maxNodeTris` option being set to `10`. This could be solved by checking to make sure that both children counts will be above the tris threshold before splitting the nodes into separate children.

**Comment by mquander** [comment]
Nice catch, that seems right.

**Comment by gkjohnson** [comment]
As discussed [here](https://github.com/gkjohnson/three-mesh-bvh/pull/59#discussion_r244258183) I think this is just an artifact of a naive split strategy and not something that should be addressed.
