### ISSUE TITLE
edgeUtils exports

### ISSUE THREAD

**Issue by lewibs-Powern** [gkjohnson/three-mesh-bvh#593]
**Is your feature request related to a problem? Please describe.**
I am trying to implement https://github.com/gkjohnson/three-mesh-bvh/blob/master/example/edgeProjection.js and I notice that many of the tools I need are in edgeUtils which don't seem to be exported.

**Describe the solution you'd like**

Could you either tell me how get these exports, or give me the green light to make a pr where these tools are all exported into index.js

**Describe alternatives you've considered**

none

**Additional context**

Super useful library you've made :)

**Comment by gkjohnson** [comment]
The files in /examples are intended to show what's possible with three-mesh-bvh and not designed or maintained in a way suitable for export. And I think that's fine as it is. You can copy the edgeUtils and edgeProjection logic into your own project, though. I may separate those files out to another project at some point, though.

> Super useful library you've made :)

Thanks!
