### ISSUE TITLE
Selection tool issue with irregular shape model

### ISSUE THREAD

**Issue by jayantpaliwal** [gkjohnson/three-mesh-bvh#594]
highlighted mesh is not showing  on correct place where I have select the area of the model.
please check the below screenshots. It works for other symmetric models like ( buildings, boxes ) but not for all. 

![image](https://github.com/gkjohnson/three-mesh-bvh/assets/9565730/b588ca7e-753f-4b5e-ac15-d9824f027d9a)
![image](https://github.com/gkjohnson/three-mesh-bvh/assets/9565730/0740014c-0dc9-4368-b3ed-e080a5329241)

**Comment by gkjohnson** [comment]
Why did you delete the bug report template and ignore the requested information?

**Comment by jayantpaliwal** [comment]
@gkjohnson  can you explain me . I did not get you.
I used the selection template in  the GLB model, but it did not selected the correct areas of model.

**Comment by gkjohnson** [comment]
You deleted the text content when [creating a new bug report](https://github.com/gkjohnson/three-mesh-bvh/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=) and did not provide any of the requested information in the template. This information, specifically the live example, is necessary to reproduce and understand the problem. If this isn't provided I'll have to close the issue.

**Comment by gkjohnson** [comment]
Closing until the necessary information is provided.
