### ISSUE TITLE
Generate a vertex displacement in one mesh according to the shape of another mesh

### ISSUE THREAD

**Issue by RobinLasserye** [gkjohnson/three-mesh-bvh#597]
I'm currently trying to dynamically modify some shapes according to others. To represent shapes with offset from their vertex from each other.

I'm looking for a feature that can generate a deformation implied by an object in another object, either internally or externally.

Of type deformShape(meshWhichDeform, meshDeformed, offset, InternalOrExternal)

Taking the example of a sphere and a cube (with a sufficient subdivision larger than the sphere) where the sphere is inside the cube, moving the sphere to the outside of the square would deform its surface to ensure that it remains inside.
In the external version, the cube would be deformed to ensure that the sphere remained outside.

The algorithm would have to be able to work with complex shapes.

I've taken a look at three-bvh-csg, but it generates cuts in the shapes, whereas I'd rather deform my meshes.

I was also interested in physics engines but given that I don't want real time deformation it didn't seem appropriate and too cumbersome.

Here an example from blender to visualize an internal deformation from the cube by the sphere:
![image](https://github.com/gkjohnson/three-mesh-bvh/assets/112935865/8f902496-8ea4-4ecb-abc8-e12a833cb98b)

**Comment by gkjohnson** [comment]
I think it's best to ask at the [three.js forum](https://discourse.threejs.org/) for something like this.
