### ISSUE TITLE
umd package missing .js

### ISSUE THREAD

**Issue by deyihu** [gkjohnson/three-mesh-bvh#600]
**Describe the bug**

 [umd package](https://unpkg.com/three-mesh-bvh@0.6.8/build/index.umd.cjs)

Browser cannot recognize `.cjs` 

The browser will not run the scripts inside

 
![NFX)`9DPJCC@SHSWUG9SSYF](https://github.com/gkjohnson/three-mesh-bvh/assets/25998927/c76cc156-0304-4799-b627-883ac2495f97)

 

**To Reproduce**

***Code***

```html
  <script type="text/javascript" src="https://unpkg.com/three@0.138.0/build/three.min.js"></script>
<script src="https://unpkg.com/three-mesh-bvh@0.6.8/build/index.umd.cjs"></script>
```

***Live example***

-

**Expected behavior**

umd package Should use js as the extension

```html
  <script type="text/javascript" src="https://unpkg.com/three@0.138.0/build/three.min.js"></script>
<script src="https://unpkg.com/three-mesh-bvh@0.6.8/build/index.umd.js"></script>
```

need update rollup config

```js
{
		input: './src/index.js',
		treeshake: false,
		external: p => /^three/.test( p ),

		output: {

			name: 'MeshBVHLib',
			extend: true,
			format: 'umd',
			file: './build/index.umd.js',
			sourcemap: true,

			globals: p => /^three/.test( p ) ? 'THREE' : null,

		},

	},

```

**Screenshots**

If applicable, add screenshots to help explain your problem (drag and drop the image).

**Platform:**

 - Device: [Desktop, Mobile, ...]
 - OS: [Windows, MacOS, Linux, Android, iOS, ...]
 - Browser: [Chrome, Firefox, Safari, Edge, ...]
 - Three.js version: [r???]
 - Library version: [v???]

**Comment by gkjohnson** [comment]
There's not browser requirement that javascript files end with a `.js` extension - this is an issue with unpkg.com setting the returned content type to "text/plain" rather than "application/javascript" in the response headers. Both .cjs and .mjs extensions are used fairly broadly to distinguish module-style js files and commonjs-style ones.
