### ISSUE TITLE
To obtain all the nearest point indices within the radius from the PCD file.

### ISSUE THREAD

**Issue by yogesh0325** [gkjohnson/three-mesh-bvh#608]
I need the best way to find all the nearest indices from the PCD file for the huge PCD file
to get the nearest indices from a simple distance method by traversing it takes a long time

**Comment by gkjohnson** [comment]
I'm unfamiliar with what a PCD file is. If it's a series of points then three-mesh-bvh is designed to support triangles. You can provide your own wrapper and mechanism for quickly measuring distances. You can see the "point cloud intersection" for an example of such a wrapper.
