### ISSUE TITLE
Iterative closest points algorithm implemantion using three-mesh-bvh

### ISSUE THREAD

**Issue by shahzeen031** [gkjohnson/three-mesh-bvh#637]
**Is your feature request related to a problem? Please describe.**

I am trying to find the best-fit alignment of two buffer geometry objects but could not find any way to achieve this in three.js.

**Describe the solution you'd like**

Implementation of ICP algorithm using BVH functions so that we can give a source point cloud and a target point cloud and get a transformation matrix?

**Describe alternatives you've considered**

I am trying to implement it with plane math vector methods but it's too complicated and time-consuming.

**Additional context**

Any guidance on what three-mesh-bvh function I can use to simplify my implementation?

**Comment by gkjohnson** [comment]
> I am trying to implement it with plane math vector methods but it's too complicated and time-consuming.

It's unclear what you mean by time consuming. Do you already have an implementation and it's slow? Either way if you need help with an algorithm please ask at the three.js forums and I recommend referring to papers on how ICP implementations.
