### ISSUE TITLE
Triangle Painting - How does it work?

### ISSUE THREAD

**Issue by KeshavUpadhyaya** [gkjohnson/three-mesh-bvh#639]
Hello,

I am trying to implement triangle painting with a custom geometry from an STL file. When I replace the torus geometry in `collectTriangles.js` with my custom geometry just 1 triangle gets painted at a time. I am really not sure why it isn't working. I used the `STLLoader` from `three/examples/jsm/loaders/STLLoader` to load my file.

I would also like to know how the below two functions work.

```javascript
      bvh.shapecast({
        intersectsBounds: (box) => {
          const intersects = sphere.intersectsBox(box);
          const { min, max } = box;
          if (intersects) {
            for (let x = 0; x <= 1; x++) {
              for (let y = 0; y <= 1; y++) {
                for (let z = 0; z <= 1; z++) {
                  tempVec.set(
                    x === 0 ? min.x : max.x,
                    y === 0 ? min.y : max.y,
                    z === 0 ? min.z : max.z
                  );
                  if (!sphere.containsPoint(tempVec)) {
                    return INTERSECTED;
                  }
                }
              }
            }

            return CONTAINED;
          }

          return intersects ? INTERSECTED : NOT_INTERSECTED;
        },

        intersectsTriangle: (tri, i, contained) => {
          if (contained || tri.intersectsSphere(sphere)) {
            const i3 = 3 * i;
            indices.push(i3, i3 + 1, i3 + 2);
          }

          return false;
        },
      });
```
Could you please help @gkjohnson ? Thanks

**Comment by gkjohnson** [comment]
The example works by traversing the BVH and finding any triangles that intersect the sphere and coloring them in the subsequent code.

> I would also like to know how the below two functions work.

The first `intersectsBounds` function is detecting intersections with the BVH bounds to check if child bounds should be checked and the second is with individual triangles in the geometry. You can read the documentation for more detail on the shapecast function.

For more information please open a question with a live example of what's not working for you at the three.js forums so others can take a look.
