### ISSUE TITLE
Some examples throwing an exception (Failed to construct 'URL')

### ISSUE THREAD

**Issue by kutu** [gkjohnson/three-mesh-bvh#640]
https://github.com/gkjohnson/three-mesh-bvh/blob/f842cd802a331bd1dcabe7bc3e3b38d1878bad92/example/diamond.js#L54

![image](https://github.com/gkjohnson/three-mesh-bvh/assets/228802/4655a341-3e45-48ee-a974-7d9e0391769b)

Same with [Lambert GPU Path Tracing](https://gkjohnson.github.io/three-mesh-bvh/example/bundle/gpuPathTracing.html)

Windows / Chrome

**Comment by gkjohnson** [comment]
Thanks - at some point I'll have to just remove Parcel, which wasn't bundling the URL correctly... Its quirks are starting to be a lot of maintenance effort.
