### ISSUE TITLE
Help wanted.

### ISSUE THREAD

**Issue by HawtinZeng** [gkjohnson/three-mesh-bvh#646]
Hi, gkjohnson, I am writing to ask some help about the source code, what is float32Array, nodeIndex32 and nodeIndex16 in function _intersectsGeometry? I can't figure out this.
![image](https://github.com/gkjohnson/three-mesh-bvh/assets/73981739/c64666fb-c311-4b19-84b2-8b70c9b2e641)

**Comment by HawtinZeng** [comment]
I have no questions about how to use this lib, I want to understand the process of testing the intersections of two geometry, but i found I can't understand these three buffers(float32Array, uint16Array, uint32Array)

**Comment by HawtinZeng** [comment]
Can u recommend some books or blogs about the buffer array in geometry?

**Comment by gkjohnson** [comment]
Do you have a specific question about that code? I'm not sure what you're asking for.

> Can u recommend some books or blogs about the buffer array in geometry?

I don't. The project just uses three.js and javascript.

**Comment by HawtinZeng** [comment]
Ok, thank u!
