### ISSUE TITLE
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file

### ISSUE THREAD

**Issue by shaofahui** [gkjohnson/three-mesh-bvh#652]
After i npm I three-mesh bvh, I import {computeBoundsTree, disposeBoundsTree, acceleratedRaycast} from 'three-mesh-bvh' in a js file, and the console reports an error: You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.

**Comment by gkjohnson** [comment]
This sounds like a build process issue - I recommend reading up on the documentation for your build system or asking at relevant forums.
