### ISSUE TITLE
Add near and far check in intersectRay

### ISSUE THREAD

**Issue by agargaro** [gkjohnson/three-mesh-bvh#657]
Adding `near` and `far` to the `intersectRay` function would avoid recursively checking many bvh nodes when raycasting.

It will require a change in the API.

I did a test by setting raycaster.far = 0.1 from raycast example page and of course it is super fast.

It would also be useful to edit the raycast example page by adding `near` and `far` in the **GUI** (which will also change the length of the drawn lines) and to use `InstancedMesh` so that raycasting can be tested better (too many drawcalls are a bottleneck).

![image](https://github.com/gkjohnson/three-mesh-bvh/assets/47436453/79df74ca-230e-4ba0-8523-4d3a8c073c87)

**Comment by gkjohnson** [comment]
This would be a good change  - currently I think the raycast results may even be incorrect if raycaster.near or far are modified.

> It will require a change in the API.

I think we can just add `near` and `far` arguments to the `.raycast` and `.raycastFirst` functions - it shouldn't be breaking.

> It would also be useful to edit the raycast example page by adding near and far in the GUI

If we do this lets change the ray lengths to help show the difference in what's happening.

> use InstancedMesh so that raycasting can be tested better (too many drawcalls are a bottleneck).

I've been meaning to do this but have never had time. Help would be great! The bvh raycasting demo I [added to three.js](https://threejs.org/examples/?q=bvh#webgl_raycaster_bvh) uses InstancedMesh for the spheres and updates a LineSegments class for all the lines.
