### ISSUE TITLE
Import error with NextJS

### ISSUE THREAD

**Issue by benjaminbours** [gkjohnson/three-mesh-bvh#659]
**Describe the bug**

I started a project with the version `0.6.8`. Everything was working as expected. When I update to `0.7.0` or any superior version, I got this compilation error (I am using nextjs `14.1.0`):

```
 ⨯ ../node_modules/three-mesh-bvh/src/index.js
Attempted import error: 'bvh_struct_definitions' is not exported from './gpu/BVHShaderGLSL.js' (imported as 'BVHShaderGLSL').

```

Which is not true, I checked the files in my `node_modules/three-mesh-bvh` folder and it's of course exported.

**To Reproduce**

1. Access a page compiled with nextjs `14.1.0` containing a client side component using `three-mesh-bvh` version at least `0.7.0`
2. See error describe earlier.

***Code***

```js
// code goes here
```

***Live example***

I have not live example yet but could deploy one if it's required. Don't know if it's relevant in that case.

**Expected behavior**

I would like the lib to load correctly, as it was the case in `0.6.8` while having the update from the last releases.

**Screenshots**

Not relevant, I already printed the error.

**Platform:**

 - Device: [Desktop]
 - OS: [MacOS]
 - Browser: [Any]
 - Three.js version: [r161]
 - Library version: At least [v0.7.0]

**Additional info**

@gkjohnson first, thank you for the great job on this lib! I am currently working on this personal project where your lib is completely key to make it possible => https://dev.compositethegame.com/en | https://github.com/benjaminbours/Composite/tree/level-builder-core-back (If you are not in europe, you will experience high latency) so without your work, it would be much more complicated for me, thank you.

My usage of this lib is probably unconventional, as I am even using it on the backend with NodeJS (there, no import problem with 0.7.0 though) because I have an authoritative server responsible to calculate the physic.

I assume you probably did something between 0.6.8 and 0.7.0 to influence the way the lib is loaded or packaged, do you remember any valuable information to solve this problem?

Thanks in advance,

Benjamin

**Comment by benjaminbours** [comment]
Ok I managed to find a hotfix to unlock my situation, in `package.json`, I did this change

```json
"module": "build/index.module.js",
```

I don't know why your `package.json` is targetting `src/index.js` but you might have your reason.

Let me know if you agree with this fix and I can make a PR if you don't have time for this

**Comment by gkjohnson** [comment]
Nothing dramatic changed in 0.7.0 - just some file refactoring. Is this something you can reproduce in a new, minimal project? Looking at the code there doesn't seem to be anything wrong and I haven't heard of issues with other bundlers and I don't use nextjs myself. 

> Let me know if you agree with this fix and I can make a PR if you don't have time for this

I'd prefer not to make this change without understanding why. Importing the original src should be better for some bundlers when it comes to treeshaking and dead code elimination. The index.module.js file is only produced because people have asked for a standalone file to download.

If this can reproduced in a minimal case and it's not looking like the project code is structured incorrectly this may be something worth reporting to nextjs.

**Comment by em3ai** [comment]
"export * as BVHShaderGLSL from './gpu/BVHShaderGLSL.js", it is a syntex error, i think

**Comment by zhoulhcn** [comment]
> Ok I managed to find a hotfix to unlock my situation, in `package.json`, I did this change
> 
> "module": "build/index.module.js",
> I don't know why your `package.json` is targetting `src/index.js` but you might have your reason.
> 
> Let me know if you agree with this fix and I can make a PR if you don't have time for this

hello do you find any other solutions，I got same error in next.js

**Comment by zhoulhcn** [comment]
@gkjohnson Please Check this issue，I got same error，I fixed it by edit package.json file，but when I reinstall the error come again
Next.js:v15.1.2
@react-three/drei:^10.0.0-rc.2
three-mesh-bvh:0.8.3

**Comment by gkjohnson** [comment]
As mentioned previously in the thread - please direct your issues to next.js. The package.json and exports are structured in a valid way supported by every other bundler. Without an explanation of what is wrong or why there is an issue nothing can be done.

**Comment by zhoulhcn** [comment]
> As mentioned previously in the thread - please direct your issues to next.js. The package.json and exports are structured in a valid way supported by every other bundler. Without an explanation of what is wrong or why there is an issue nothing can be done.

Thanks reply

**Comment by zhoulhcn** [comment]
I find where the problem is, Is cause I use raw-loader plugin in next.config

**Comment by returningsam** [comment]
> I find where the problem is, Is cause I use raw-loader to load glsl files, delete raw-loader config in next.config and there is no error

Agreed with @gkjohnson that this (very likely) not a bug with `three-mesh-bvh`.

However, to elaborate for anyone else who finds this, it seems the following (example) webpack config rule will cause the aforementioned build error:

```javascript
config.module.rules.push({
  test: /\.glsl/,
  // rest of the config
});
```

I was able to fix this issue by instead using `.vert` and `.frag` file extensions for my shader files, and changing the webpack rules accordingly:

```javascript
config.module.rules.push({
  test: /\.(vert|frag)/,
  // rest of the config
});
```
