### ISSUE TITLE
Compute bounds tree after adding mesh to group/scene?

### ISSUE THREAD

**Issue by neilrackett** [gkjohnson/three-mesh-bvh#662]
We're using BVH to boost the performance of a small number of features in a larger app, computing the bounds tree before adding the associated mesh to either a group or a scene. This works well, but adds time at startup for something that may never get used.

What I'd like to do is compute the bounds tree, either using a Worker or on-demand, _after_ a mesh has been added to a group and/or scene, but find that running `computeBoundsTree()` or `new MeshBVH(geom)` after the associated mesh has been added to something else, even if it hasn't been added to the scene, the script just hangs. Forever.

So I just wanted to ask if this is actually possible?

**Example**

```javascript
const geom = new THREE.TorusKnotBufferGeometry( 10, 3, 400, 100 );
const mesh = new THREE.Mesh( geom, material );
const group = new THREE.Group();

group.add(mesh);
geom.computeBoundsTree();

// It never gets here
```

**Comment by gkjohnson** [comment]
This should work just fine and have no impact on the generation time of the BVH itself. Do you have a live example using something like jsfiddle showing the issue?

**Comment by neilrackett** [comment]
I'll put a fiddle or similar together -- is there an existing template I can use that takes care of the boilerplate?

**Comment by gkjohnson** [comment]
This official three.js one is a reasonable one to start with:

https://jsfiddle.net/v98k6oze/

**Comment by neilrackett** [comment]
OK, so it [works fine in a fiddle](https://jsfiddle.net/neilrackett/2aw5p9sz/8/), so looks like the issue is somehow specific to our viewer / models.

I'll post an update here if I identify a real bug 😉
