### ISSUE TITLE
a syntex error in index.js when import from 'three-mesh-bvh'

### ISSUE THREAD

**Issue by em3ai** [gkjohnson/three-mesh-bvh#668]
when i import from three-mesh-bvh, there is a syntex error: "export * as BVHShaderGLSL from './gpu/BVHShaderGLSL.js';" this statement is not standard.

The log is as follows:
Module parse failed: Unexpected token (12:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| export * from './gpu/VertexAttributeTexture.js';
| export * from './utils/StaticGeometryGenerator.js';
> export * as BVHShaderGLSL from './gpu/BVHShaderGLSL.js';
| 
| // backwards compatibility

**Comment by gkjohnson** [comment]
`export * as ...` is [perfectly legal syntax](https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export) in javascript. If it's not working please check your bundler settings or report it to the bundler project.

**Comment by Fate-ui** [comment]
configuring the following code in `vue.config.js` solved my problem
`  transpileDependencies: ['three-mesh-bvh']
`
