### ISSUE TITLE
Not able to find any *.generated and *_indirect js files in your repository

### ISSUE THREAD

**Issue by nnvvijay** [gkjohnson/three-mesh-bvh#672]
HI,

In my application, I am using your library which is the old version.

Now I am trying to update to the latest version but it's not working because of missing files.

Below are some of the example files that are referred to but not available in your master repository 

few of them are as below
[MeshBVH.js](https://github.com/gkjohnson/three-mesh-bvh/blob/master/src/core/MeshBVH.js):

import { iterateOverTriangles } from './utils/iterationUtils.generated.js';
import { refit } from './cast/refit.generated.js';
import { raycast } from './cast/raycast.generated.js';
import { raycastFirst } from './cast/raycastFirst.generated.js';
import { intersectsGeometry } from './cast/intersectsGeometry.generated.js';
import { closestPointToGeometry } from './cast/closestPointToGeometry.generated.js';

And buildTree.js
import { partition } from './sortUtils.generated.js';
import { partition_indirect } from './sortUtils_indirect.generated.js';

these are some examples. Let me know how to solve this

**Comment by nnvvijay** [comment]
I am using your library in a static web page. Previously I use to download and include in my code

**Comment by gkjohnson** [comment]
These files are built on package release and not available in the project repository. You can get them through the published NPM package or one of the [CDNs that mirrors those packages](https://unpkg.com/browse/three-mesh-bvh@0.7.5/build/).
