### ISSUE TITLE
getBoundingBox box very slightly bigger than threejs bounding box

### ISSUE THREAD

**Issue by ToyboxZach** [gkjohnson/three-mesh-bvh#680]
**Describe the bug**

Calling: 

On a BoxGeometry geometry creates a bounding box that is very slightly bigger than the geometry itself

**To Reproduce**
```
const boxGeo = new BoxGeometry(width, depth, height);
const bvh =  new MeshBVH(boxGeo);
const box = new Box3();
bvh.getBoundingBox(box);
vs
boxGeo.computeBoundingBox()
```
Expect that to be nice round numbers of 0.5 -> -0.5 instead it adds just a little bit to the edge of each edge.
![image](https://github.com/gkjohnson/three-mesh-bvh/assets/64285391/915c6cee-037c-4d5a-acbb-aaa88d03bcd4)

Maybe I misunderstand the purpose of this bounding box, but this ended up causing us problems because we wanted to get the center of the geometry and it was just barely off for some less symetrical cases

**Comment by gkjohnson** [comment]
The bounds of the BVH are stored as half-widths and expanded by [a small epsilon](https://github.com/gkjohnson/three-mesh-bvh/blob/4a59ceaa3495c1b6f371781e020105fe47cadfc1/src/core/build/computeBoundsUtils.js#L170-L171) (specifically `2^-24`) to account for floating point error and ensure that the triangles are correctly contained (see #169, #170).

What specific issue is this causing for you?

**Comment by ToyboxZach** [comment]
Ah ok, we are using this bounding box incorrectly then. We were just depending on it to get the exact center of an object to be able to adjust a geometry’s position.

Maybe it’s an issue that it’s not symmetrical but doesn’t seem like this is the purpose of this bounding box

**Comment by gkjohnson** [comment]
If you'd like to adjust the documentation to help make the behavior more clear I'd be open to a PR. Also note that by default that bounding box will be assigned to the geometry when generating the BVH if it hasn't already been generated. This behavior can be disabled with setting the `setBoundingBox` option to `false`, though.
