### ISSUE TITLE
TS type augmentations don't work w/ "moduleResolution": "node16"

### ISSUE THREAD

**Issue by fabis94** [gkjohnson/three-mesh-bvh#682]
**Describe the bug**

This package augment's some of three.js' types, but it doesn't do it correctly, at least according to modern Node/TypeScript module resolution logic.

Example:
https://github.com/gkjohnson/three-mesh-bvh/blob/4a59ceaa3495c1b6f371781e020105fe47cadfc1/src/index.d.ts#L210-L222

The three.js module path is lacking a file extension. Once I added a file extension to those `declare module XX` import paths manually inside of node_modules, TS picked up on the types and they started working.

More info from TS docs: https://www.typescriptlang.org/tsconfig/#moduleResolution

**To Reproduce**

Install three.js & three-mesh-bvh in a TS project w/ modern Node module & moduleResolution settings (node16 or nodenext). The three-mesh-bvh type augmentations will not be applied.

**Expected behavior**

The package should define TS types correctly in accordance to modern Node/TS module resolution logic.

**Platform:**

 - Three.js version: 165
 - Library version: 0.7.5
 - TypeScript version: 5.2.2

**Comment by gkjohnson** [comment]
Should this line

```ts
declare module 'three/src/core/BufferGeometry'
```

be changed to this?

```ts
declare module 'three'
```

Unfortunately I'm not a typescript expert so please feel free to make a PR if you have a fix.

**Comment by fabis94** [comment]
@gkjohnson You'd just need to add file extensions to those relative module specifiers: 'three/src/core/BufferGeometry.js' and 'three/src/core/Raycaster.js' respectively

**Comment by gkjohnson** [comment]
Is it possible to use `declare module 'three'`, instead, and put both class modifications in the same block? That would be nicer, I think. If you could test and make a PR that would be much appreciated.
