### ISSUE TITLE
Should there be otherRoots[j] instead of otherRoots[i] in function bvhcast () ?

### ISSUE THREAD

**Issue by tianjian-sky** [gkjohnson/three-mesh-bvh#688]
<img width="1338" alt="image" src="https://github.com/user-attachments/assets/b477f939-c1a9-4759-92e1-3ec0958a8f3a">

**Comment by gkjohnson** [comment]
Yes! Very nice catch. Would you like to make a PR with the fix?

**Comment by tianjian-sky** [comment]
> Yes! Very nice catch. Would you like to make a PR with the fix?
[pr #689](https://github.com/gkjohnson/three-mesh-bvh/pull/689)

**Comment by gkjohnson** [comment]
Fixed in #689
