### ISSUE TITLE
How to use in a large number of point clouds

### ISSUE THREAD

**Issue by mqly11** [gkjohnson/three-mesh-bvh#691]
I am loading the point cloud (many points objects) after the block in the project, I want to use bvh to improve the click efficiency of my ray, what should I do, hope to guide, thank you.

**Comment by gkjohnson** [comment]
Point clouds are not directly supported by the project but it's possible to implement point cloud intersection using the "shapecast" function. See the [point cloud intersection example](https://gkjohnson.github.io/three-mesh-bvh/example/bundle/pointCloudIntersection.html).
