### ISSUE TITLE
BVHShaderGLSL is not available for typescript

### ISSUE THREAD

**Issue by obrhaberer** [gkjohnson/three-mesh-bvh#694]
**Describe the bug**

BVHShaderGLSL is not available for typescript.

**To Reproduce**

BVHShaderGLSL inside project.

***Code***

import { BVHShaderGLSL } from 'three-mesh-bvh'

***Live example***

-

**Expected behavior**

BVHShaderGLSL part of index.d.ts

**Screenshots**

**Platform:**

 - Device: Desktop
 - OS: MacOS
 - Browser: Chrome
 - Three.js version: latest
 - Library version: latest

**Comment by gkjohnson** [comment]
Thanks! Can you make a PR with the addition?

**Comment by gkjohnson** [comment]
Fixed in #697
