### ISSUE TITLE
Request for an example using Raycasting, GLTF, and Pmndrs/Postprocessing Outline

### ISSUE THREAD

**Issue by kitaedesigns** [gkjohnson/three-mesh-bvh#716]
**Is your feature request related to a problem? Please describe.**

Raycasting three.js primitives isn't super helpful for an example using this library since their polycount is so low, but raycasting and selecting between multiple high poly objects is and would probably show off the utility of this library versus the standard raycaster much better. 

**Describe the solution you'd like**

A simple demo with a few gltf's that one can click on to select using raycasting and get highlighted would be great. That's pretty much how every 3D app has decided to best showcasing something being selected.

**Describe alternatives you've considered**

I've been using the older raycaster since it's so easy to setup, but this library is much better.

**Additional context**

**Comment by gkjohnson** [comment]
Can you demonstrate what you've tried? The mechanics for raycasting don't change with the library and generating a BVH doesn't change whether a geometry is a three.js primitive or a mesh object from a GLTF. Everything you need is already in the "Use" section of the README.
