### ISSUE TITLE
Performance 

### ISSUE THREAD

**Issue by RyugaRyuzaki** [gkjohnson/three-mesh-bvh#730]
I try to create geometry : 
- Setup BVH
```
 import {BufferGeometry, Mesh} from "three";
import {
  computeBoundsTree,
  disposeBoundsTree,
  acceleratedRaycast,
} from "three-mesh-bvh";

// Source: https://github.com/gkjohnson/three-mesh-bvh
export class BVH {
  private static initialized = false;

  static apply(geometry: BufferGeometry) {
    if (!BVH.initialized) {
      //@ts-ignore
      BufferGeometry.prototype.computeBoundsTree = computeBoundsTree;
      //@ts-ignore
      BufferGeometry.prototype.disposeBoundsTree = disposeBoundsTree;
      Mesh.prototype.raycast = acceleratedRaycast;
      BVH.initialized = true;
    }
    //@ts-ignore
    if (!geometry.boundsTree) {
      //@ts-ignore
      geometry.computeBoundsTree();
    }
  }

  static dispose(geometry: BufferGeometry) {
    //@ts-ignore
    geometry.disposeBoundsTree();
  }
}
```
Then i create geometry : 
```
    /**
   *
   */
  private static newModelGeometry(
    PositionArray: number[],
    ColorArray: number[],
    ElementIdArray: number[],
    IndexArray: number[]
  ) {
    const before = performance.now();
    console.log("PositionArray Length:", PositionArray.length);
    console.log("ColorArray Length:", ColorArray.length);
    console.log("ElementIdArray Length:", ElementIdArray.length);
    console.log("IndexArray Length:", IndexArray.length);
    const geometry = new THREE.BufferGeometry() as IMergeMeshBufferGeometry;
    geometry.setAttribute(
      "position",
      new THREE.BufferAttribute(new Float32Array(PositionArray), 3)
    );
    geometry.setAttribute(
      "color",
      new THREE.BufferAttribute(new Float32Array(ColorArray), 3)
    );
    geometry.setAttribute(
      "elementId",
      new THREE.BufferAttribute(new Uint32Array(ElementIdArray), 1)
    );
    geometry.setIndex(IndexArray);

    geometry.computeVertexNormals();
    geometry.computeBoundingBox();
    geometry.computeBoundingSphere();
    BVH.apply(geometry);
    console.log(`Time total:${performance.now() - before}ms`);
    return geometry;
  }
```
This is result : 
```
PositionArray Length: 5927865
MergeMesh.ts:137 ColorArray Length: 5927865
MergeMesh.ts:138 ElementIdArray Length: 1975955
MergeMesh.ts:139 IndexArray Length: 10259733
MergeMesh.ts:159 Time total:5965.70000000298ms
```
But when i remove : 
```
//@ts-ignore
    if (!geometry.boundsTree) {
      //@ts-ignore
      geometry.computeBoundsTree();
    }
```
And result : 
```
PositionArray Length: 5927865
MergeMesh.ts:137 ColorArray Length: 5927865
MergeMesh.ts:138 ElementIdArray Length: 1975955
MergeMesh.ts:139 IndexArray Length: 10259733
MergeMesh.ts:159 Time total:1735.0999999940395ms
```

**Comment by gkjohnson** [comment]
Please state what your question is and fill out the issue template provided when selecting "bug" in the issue creation stage. Closing for now.

**Comment by RyugaRyuzaki** [comment]
hi @gkjohnson the problem when i have a big geometry size, this function takes some time to call : 
```
  if (!geometry.boundsTree) {
      //@ts-ignore
      geometry.computeBoundsTree();
    }
```

**Comment by gkjohnson** [comment]
Computing a BVH is not cheap. If you have a large geometry it should be expected that the function will take some time. If you'd like to reduce any performance hiccups you can compute the BVH using [a web worker](https://github.com/gkjohnson/three-mesh-bvh?tab=readme-ov-file#asynchronous-generation).

**Comment by RyugaRyuzaki** [comment]
> Computing a BVH is not cheap. If you have a large geometry it should be expected that the function will take some time. If you'd like to reduce any performance hiccups you can compute the BVH using [a web worker](https://github.com/gkjohnson/three-mesh-bvh?tab=readme-ov-file#asynchronous-generation). Or you can look into generating a BVH ahead of time, saving it, and loading it at run time. Though this isn't officially supported or documented.

Thank you. Now i can understand why it's a little slow.

**Comment by RyugaRyuzaki** [comment]
> Computing a BVH is not cheap. If you have a large geometry it should be expected that the function will take some time. If you'd like to reduce any performance hiccups you can compute the BVH using [a web worker](https://github.com/gkjohnson/three-mesh-bvh?tab=readme-ov-file#asynchronous-generation). Or you can look into generating a BVH ahead of time, saving it, and loading it at run time. Though this isn't officially supported or documented.

And can i ass one more question what 's the different  if i : 
```
geometry.boundsTree = new MeshBVH(geometry) 
```
Instead of : 
```
 geometry.computeBoundsTree();
```

**Comment by gkjohnson** [comment]
You can use either method.
