### ISSUE TITLE
Possible Bug For Uniform Surfaces

### ISSUE THREAD

**Issue by obsius** [gkjohnson/three-mesh-bvh#93]
First off, thanks for this library, works great.  I recently moved off of the THREE.Octree package and saw this one listed as an alternative.  I've seen better performance in most scenarios, and I like the indexing options, but either I'm doing something really stupid, or the indexing strategies aren't working with near-evenly-distributed points on a surface.

Here is an evenly distributed surface, along a plane:
![no](https://user-images.githubusercontent.com/20999862/54353427-47881600-4611-11e9-9a2b-6e8f2bdcd523.PNG)

Close up:
![no_zoom](https://user-images.githubusercontent.com/20999862/54353715-f88eb080-4611-11e9-9cf8-916798cc2328.PNG)

Evenly distributed surface (different elevations):
![no_2](https://user-images.githubusercontent.com/20999862/54353756-12c88e80-4612-11e9-94bc-a095d51ccf52.PNG)

Non-uniform surface (works):
![yes](https://user-images.githubusercontent.com/20999862/54353784-27a52200-4612-11e9-83c8-f14e638b250d.PNG)

Close up:
![yes_zoom](https://user-images.githubusercontent.com/20999862/54353837-3f7ca600-4612-11e9-9c84-b69a7a62e307.PNG)

In these screenshots, it's AVERAGE / 64 / 16.  The performance of the non-uniform surface for ray casting is fantastic, but the uniform surface ray casting is 100x slower and doesn't even work with the missing bounds.

**Comment by gkjohnson** [comment]
Hey @obsius, thanks for submitting the issue!

It does look like the bounds aren't being constructed properly in the first few pictures. Do you have a code example we can run so to recreate the issue?

**Comment by obsius** [comment]
Thanks for the quick reply.  I saw the bug posted after mine ([issue 94](https://github.com/gkjohnson/three-mesh-bvh/issues/94)) and figured they may be related, sure enough, I made his fix, and this is the result now:
![image](https://user-images.githubusercontent.com/20999862/54392756-a9726b00-4665-11e9-8bf9-84e2603d367c.png)

So it wasn't the spacing of the points, but rather the number of them, I guess my processed surfaces were just in that sweet spot where number of triangles vs vertices caused the overflow.

**Comment by gkjohnson** [comment]
Heh I figured it might be the same issue. I'll try to have a new version with the fix pushed out to NPM in the next few days or so. I'll let you know when it's out.

And can I ask what you're using the library for? I always like to hear how my projects are being used.

Thanks again for submitting the issue!

**Comment by gkjohnson** [comment]
This has been fixed in [v0.1.1](https://github.com/gkjohnson/three-mesh-bvh/releases/tag/v0.1.1).

Thanks again!

**Comment by obsius** [comment]
@gkjohnson Thanks for the fix.  I'm building a commercial optimizer for ore control in the mining space, and use THREE to visualize topographies (like the screenshots above) among other features of an open pit mine.  Calculations require lots ray casting against the topos and having the data indexed makes a huge difference in processing time.  Thanks again for providing this.
