### ISSUE TITLE
Possible bug in _ensureIndex( )

### ISSUE THREAD

**Issue by Domenicobrz** [gkjohnson/three-mesh-bvh#94]
In a BufferGeometry the index array is an array that specifies a list of vertex-indices with either Uint16 or Uint32 arrays

Here:
`const index = new ( triCount > 65535 ? Uint32Array : Uint16Array )( indexCount );`

You're looking for a triangle count > 65535 to switch to Uint32 arrays whereas I believe that the correct value to check would be the number of vertices, not triangles

e.g.:  assume you have 70000 vertices in a mesh, now you need to push the vertex index 70000 inside the index array -- you can't! since the triangle count is fixed at a third of that value and a Uint16 array was used instead

Checking for vertex count instead of triangles count solved the bug I was having

**Comment by gkjohnson** [comment]
Hey @Domenicobrz thanks for submitting the issue! You're right, it looks like it should be using the position attribute count, instead -- good catch!

Would you like to submit a PR and maybe an associated test?

Also can I ask what you're using the library for? I'm always interested to hear what projects are benefiting!

**Comment by Domenicobrz** [comment]
Unfortunately I don't have a lot of experience with pull requests / testing frameworks, I'll have to leave that part to you! :) I barely know how to setup a git repo

At work we needed a tool to "color" every face of a mesh that was inside the radius of a circled cursor, most of the calculations are done with texture data and a simple shader pass, but knowing the exact point in space where the center of the cursor was hitting the mesh helped immensely in discarding faces that were being projected in that bidimensional radius, but were too "far away" in 3d space

Thank you for your amazing work, I'm sure I'll use your library again in the future since it's so useful

**Comment by gkjohnson** [comment]
@Domenicobrz glad to hear it! I'll fix this in the next release.

Thanks again for filing the issue!
